BUILD_VER=$(date +'%m%d')

LATEST_VER="latest"

MSYS2_VER="20250221"
PYTHON_VER="3.13.4"

ATMO_VER="1.9.1"
ATMO_HASH="b11850b3a"
HBL_VER="2.4.4"
HBMENU_VER="3.6.0"

HEKATE_VER="6.3.1"
NYX_VER="1.7.0"

DEEPSEA_VER="4.13.0"
KEFIR_VER="767"
HATS_VER="20.1.0-1.1"
HATS_HASH="jg00nl589tml0gv"

[latest_version]
ultrahand_version=1.8.3
tester_version=0510
toolkit_version=1.6.0
kip_version=1.6.0
eos_version=1.1.4
mtn_version=2.1.1