;override=Sys-ClkOC Toolkitloader.kip 관리 도구
;creator=Asa
;color=red

[@]
[Sys-Clk]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Sys-Clk' = ' 앱의 사용 여부 선택'

[support]
;mode=table
;alignment=right
;gap=30
;section_text_color=section
;info_text_color=accent
'' = '기본 지원 범위의 안정된 클럭 값 사용'

[활성화]
;mode=toggle
on:
rename '/atmosphere/contents/00FF0000636C6BFF_/' '/atmosphere/contents/00FF0000636C6BFF/'
del 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
del '/config/sys-clk/config.ini'
del '/switch/.overlays/sys-clk-overlay.ovl'
cp '/switch/.packages/.offload/oc/EOS.nsp' 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
cp '/switch/.packages/.offload/oc/EOS.ini' '/config/sys-clk/config.ini'
cp '/switch/.packages/.offload/oc/EOS.ovl' '/switch/.overlays/sys-clk-overlay.ovl'
set-ini-val '/config/ultrahand/sys-clk.ini' 'status' enabled 1
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
exit
off:
rename '/atmosphere/contents/00FF0000636C6BFF/' '/atmosphere/contents/00FF0000636C6BFF_/'
del 'atmosphere/contents/00FF0000636C6BFF_/exefs.nsp'
del '/config/sys-clk/config.ini'
del '/atmosphere/kips/loader.kip'
del '/switch/.overlays/sys-clk-overlay.ovl'
cp '/switch/.packages/.offload/oc/EOS.nsp' 'atmosphere/contents/00FF0000636C6BFF_/exefs.nsp'
cp '/switch/.packages/.offload/oc/EOS.ini' '/config/sys-clk/config.ini'
cp '/switch/.packages/.offload/oc/EOS.ovl' '/switch/.overlays/sys-clk-overlay.ovl'
set-ini-val '/config/ultrahand/sys-clk.ini' 'status' enabled 0
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'true'
exit

[blank]
;mode=table
;background=false
;gap=40

[kip editor]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Sys-Clk 전환 도구' = ' Sys-ClkHorizon-OC'

[support]
;mode=table
;alignment=right
;spacing=3
;gap=0
;section_text_color=section
;info_text_color=accent
' 클럭:' = 'Sys-Clk 기본 ｜ Horizon-OC 커스텀'
' ' = ''

[notice]
;mode=table
;alignment=right
;spacing=3
;gap=0
;section_text_color=warning
;info_text_color=warning
'' = 'Horizon-OC는 loader.kip을 수동 조작하여'
'' = '안정 범위 밖의 클럭까지 조정할 수 있습니다'
'' = '낸드에 치명적인 손상을 초래할 수 있으므로'
'' = '시스낸드에서의 편집/사용을 피해주십시오'
' ' = ''

[notice]
;mode=table
;alignment=right
;spacing=3
;gap=30
;section_text_color=section
;info_text_color=accent
'' = '선택시 활성화되며 자동으로 재부팅합니다'

[Sys-Clk]
try:
rename '/atmosphere/contents/00FF0000636C6BFF_/' '/atmosphere/contents/00FF0000636C6BFF/'
del 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
del '/atmosphere/kips/loader.kip'
del '/switch/.overlays/sys-clk-overlay.ovl'
cp '/backup/kips/.OC/EOS.kip' '/atmosphere/kips/loader.kip'
cp '/switch/.packages/.offload/oc/EOS.nsp' 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
cp '/switch/.packages/.offload/oc/EOS.ini' '/config/sys-clk/config.ini'
cp '/switch/.packages/.offload/oc/EOS.ovl' '/switch/.overlays/sys-clk-overlay.ovl'
set-ini-val './config.ini' 'Sys-Clk' footer '사용중'
set-ini-val './config.ini' 'Horizon-OC' footer ''
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
reboot ini CFW

[Horizon-OC]
try:
rename '/atmosphere/contents/00FF0000636C6BFF_/' '/atmosphere/contents/00FF0000636C6BFF/'
del 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
del '/atmosphere/kips/loader.kip'
del '/switch/.overlays/sys-clk-overlay.ovl'
cp '/backup/kips/.OC/HOC.kip' '/atmosphere/kips/loader.kip'
cp '/switch/.packages/.offload/oc/HOC.nsp' 'atmosphere/contents/00FF0000636C6BFF/exefs.nsp'
cp '/switch/.packages/.offload/oc/HOC.ini' '/config/sys-clk/config.ini'
cp '/switch/.packages/.offload/oc/HOC.ovl' '/switch/.overlays/sys-clk-overlay.ovl'
set-ini-val './config.ini' 'Sys-Clk' footer ''
set-ini-val './config.ini' 'Horizon-OC' footer '사용중'
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
reboot ini CFW
