;override=Sys-ClkOC Toolkitloader.kip 관리 도구
;creator=Asa
;color=red

[@]
[Sys-Clk]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Sys-Clk' = ' 앱의 사용 여부 선택'

[활성화]
;mode=toggle
on:
rename '/atmosphere/contents/00FF0000636C6BFF_/' '/atmosphere/contents/00FF0000636C6BFF/'
del '/atmosphere/logs/sys-patch.log'
del '/switch/.packages/OC Toolkit/erista/gpu_uv3_e.json'
del '/switch/.packages/OC Toolkit/erista/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/erista/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/cpu_voltages.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_uv3_e.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_vmax.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vddq.json'
del '/switch/.packages/OC Toolkit/backup_info.ini'
del '/switch/.packages/OC Toolkit/custom_table.ini'
del '/switch/.packages/OC Toolkit/info.ini'
del '/switch/.packages/OC Toolkit/update.ini'
set-ini-val '/config/ultrahand/sys-clk.ini' 'status' enabled 1
set-ini-val './config.ini' 'EOS Toolkit' footer ''
set-ini-val './config.ini' 'SC Toolkit' footer ''
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'System Clock+' hide 'false'
exit
off:
rename '/atmosphere/contents/00FF0000636C6BFF/' '/atmosphere/contents/00FF0000636C6BFF_/'
rename '/atmosphere/contents/420000000000000B/' '/atmosphere/contents/420000000000000B_/'
del '/atmosphere/logs/sys-patch.log'
del '/atmosphere/kips/loader.kip'
del '/switch/.packages/OC Toolkit/erista/gpu_uv3_e.json'
del '/switch/.packages/OC Toolkit/erista/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/erista/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/cpu_voltages.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_uv3_e.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_vmax.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vddq.json'
del '/switch/.packages/OC Toolkit/backup_info.ini'
del '/switch/.packages/OC Toolkit/custom_table.ini'
del '/switch/.packages/OC Toolkit/info.ini'
del '/switch/.packages/OC Toolkit/update.ini'
set-ini-val '/config/ultrahand/sys-clk.ini' 'status' enabled 0
set-ini-val './config.ini' 'EOS Toolkit' footer ''
set-ini-val './config.ini' 'SC Toolkit' footer ''
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'true'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' hide 'true'
set-ini-val '/config/ultrahand/packages.ini' 'System Clock+' hide 'false'
exit

[blank]
;mode=table
;background=false
;gap=27

[kip editor]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Loader.kip 편집 도구' = ' 선택시 자동 재부팅'

[notice]
;mode=table
;alignment=right
;spacing=3
;gap=0
;section_text_color=warning
;info_text_color=warning
'' = '낸드에 치명적인 손상을 초래할 수 있습니다'
'' = '시스낸드에서의 편집/사용을 피해주십시오'
' ' = ''

[cpu_voltages]
;mode=table
;alignment=right
;spacing=3
;gap=0
;section_text_color=header
;info_text_color=accent
'CPU 전압 허용 범위' = '단위: mV'
' ' = ''

[chart_info]
;mode=table
;alignment=left
;offset=85
;spacing=2
;gap=0
;info_text_color=section
'　 구분' = '｜　　   EOS   　　｜　　   SC'
'¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯' = ''

[chart_mariko]
;system=mariko
;mode=table
;alignment=left
;offset=85
;spacing=5
;gap=27
;info_text_color=accent
'   Vddq' = '｜ 550 - 650         ｜  370 - 650'
'   Vdd2' = '｜ 1050 - 1212.5  ｜  912.5 - 1350'
'Max CPU' = '｜ 1100 - 1160     ｜  900 - 1235'
'Max GPU' = '｜ 800 - 850         ｜  800 - 960'

[chart_erista]
;system=erista
;mode=table
;alignment=left
;offset=85
;spacing=5
;gap=27
;info_text_color=accent
'   Vdd2' = '｜ 1050 - 1237.5  ｜  912.5 - 1350'
'Max GPU' = '｜ 700 - 995         ｜  700 - 950'

[EOS Toolkit]
try:
rename '/atmosphere/contents/420000000000000B_/' '/atmosphere/contents/420000000000000B/'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' custom_name 'EOS Toolkit'
set-ini-val '/config/ultrahand/packages.ini' 'SC Toolkit' custom_name 'EOS Toolkit'
cp '/backup/kips/.OC/loader.kip' '/atmosphere/kips/loader.kip'
cp '/switch/.packages/OC Toolkit/data/EOS/erista/' '/switch/.packages/OC Toolkit/erista/'
cp '/switch/.packages/OC Toolkit/data/EOS/mariko/' '/switch/.packages/OC Toolkit/mariko/'
cp '/switch/.packages/OC Toolkit/data/EOS/backup_info.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/EOS/custom_table.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/EOS/info.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/EOS/update.ini' '/switch/.packages/OC Toolkit/'
set-ini-val './config.ini' 'EOS Toolkit' footer '사용중'
set-ini-val './config.ini' 'SC Toolkit' footer ''
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'System Clock+' hide 'true'
reboot ini CFW

[SC Toolkit]
try:
rename '/atmosphere/contents/420000000000000B_/' '/atmosphere/contents/420000000000000B/'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' custom_name 'SC Toolkit'
set-ini-val '/config/ultrahand/packages.ini' 'EOS Toolkit' custom_name 'SC Toolkit'
cp '/backup/kips/.OC/loader.kip' '/atmosphere/kips/loader.kip'
cp '/switch/.packages/OC Toolkit/data/SC/erista/' '/switch/.packages/OC Toolkit/erista/'
cp '/switch/.packages/OC Toolkit/data/SC/mariko/' '/switch/.packages/OC Toolkit/mariko/'
cp '/switch/.packages/OC Toolkit/data/SC/backup_info.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/SC/custom_table.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/SC/info.ini' '/switch/.packages/OC Toolkit/'
cp '/switch/.packages/OC Toolkit/data/SC/update.ini' '/switch/.packages/OC Toolkit/'
set-ini-val './config.ini' 'EOS Toolkit' footer ''
set-ini-val './config.ini' 'SC Toolkit' footer '사용중'
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'System Clock+' hide 'true'

mariko:
reboot ini CFW

erista:
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 176 D007
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 180 D007
reboot ini CFW
