;override=간이 설명서오류 코드
;creator=Asa

[@이전 페이지]
[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'버전 오류' = ' Horizon OSGame'

[error_version]
;mode=table
;spacing=5
;gap=30
;section_text_color=section
;info_text_color=section
'2000-0000' = '2002-0007   　　2002-0008'
'2002-2536' = '2122-0082   　　2124-3000'
'2162-0101' = '2164-0020 　　　　　　　　'

[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'SD 카드 오류' = ' Micro SD'

[error_sdmc]
;mode=table
;spacing=5
;gap=30
;section_text_color=section
;info_text_color=section
'2002-0001' = '2002-4301　∼　2002-4463'
'2002-3005' = '2005-0005          　　　　　'

[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'저장소 오류' = ' Storage'

[error_storage]
;mode=table
;spacing=5
;gap=30
;section_text_color=section
;info_text_color=section
'2002-4501　∼　2002-4535' = '2002-4683'
'2002-4641　∼　2002-4660' = '2002-4690'
'2002-4741　∼　2002-4760' = '2002-6201'
'2005-0003' = '2016-0601             　　　　'

[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'기타 오류' = ' Hardware · eShop · BAN'

[error_etc]
;mode=table
;spacing=5
'2153-0321' = 'Headphone JackCartridge'
'2162-0002' = 'Joy-ConJoy-Con Rail'
'2813-1400' = 'eShop User data'
'2813-0055' = 'eShop DataParental control'
'2813-6838' = 'eShop Code'
'2124-4007, 2124-4508, 2124-5114' = 'BAN'

[@다음 페이지]
[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Switch Online Service 오류' = ' Online'

[error_online]
;mode=table
;spacing=5
;gap=30
;section_text_color=section
;info_text_color=section
'2124-3080' = ''

[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'서버 오류' = ' Server'

[error_server]
;mode=table
;spacing=5
;gap=30
;section_text_color=section
;info_text_color=section
'2124-5002' = '2124-5200   　　2124-5249'
'2811-7503' = '2811-7504   　　2816-0700'
'2817-0700' = ''

[error]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'네트워크 오류' = ' Network'

[error_net]
;mode=table
;spacing=5
;section_text_color=section
;info_text_color=section
'2110-1XXX   ∼   2110-3XXX' = '2110-1100'
'2110-2003' = '2110-2004         2110-2091'
'2110-2200' = '2110-2201         2110-2214'
'2110-3127' = '2110-3400         2124-8006'
'2124-8007' = '2124-8028         2137-0240'
'2137-8006' = '2160-0103         2160-0202'
'2306-0501' = '2306-0502         2306-0520'
'2306-0819' = '2618-0006         2618-0201'
'2618-0203' = '2618-0501         2618-0502'
'2618-0513' = '2618-0516         2618-2003'
'2810-1224' = '2811-5001         2618-0542'
'2801-7002' = '2801-7199         2810-1500'
