;override=간이 설명서오류 코드
;creator=Asa

[@]
[fatal_forwarder]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'글로벌 오류' = ' NSP 포워더 (바로가기)'

[fatal_nsp]
;mode=table
;alignment=left
;offset=180
;spacing=8
'0104444444440000' = ': hbmenu'
'01446530ACA7E000' = ': sphaira'

[blank]
;mode=table
;background=false
;gap=25

[fatal_frequent]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=accent
'유저 환경에 따라 발생하는 오류' = ''

[fatal_frequent_app]
;mode=table
;alignment=left
;offset=180
;spacing=8
'01000XXXXXXXX000' = ': Game CheatsMode'
'420000000007E51A' = ': Tesla Memory Crash'
'00FF0000636C6BFF ' = ': sys-clkOverclock'
'010000000000bd00' = ': Old MissionControl'
'0100000000001000' = ': uLaunchTheme'
'0100000000001003' = ': 3rd party controller'
'0100000000001007' = ': User selection'
'010000000000100A' = ': Web browser'
'010000000000100B' = ': eShop'
'010000000000100F' = ': File browser'
'0100000000001010' = ': Online'
'0100000000001013' = ': User play log'
'010000000000d609 ' = ': dmnt gen2/Breeze'
