;override=간이 설명서오류 코드
;creator=Asa

[@가이드]
[ultrahand]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Ultrahand' = ' 전반적인 터치 조작 가능'

[key_map]
;mode=table
;alignment=left
;offset=220
;spacing=5
;gap=28
;section_text_color=header
'- 이동:       ' = '- 메뉴:      　　'
'- 설정:  ' = '- 즐겨찾기:      '
'- 선택:  ' = '- 취소:      　　'

[package+]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Package+' = ' ASAP 패키지 설명서'

[asap_pack]
;mode=table
;alignment=left
;offset=145
;spacing=3
;gap=28
'Extra Setting+   :' = '시스템 세부 설정 편집'
'System Clock+ :' = 'Sys-ClkOC Toolkit 활성화'
'OC Toolkit　　 :' = 'Loader.kip 편집 도구'
'Launcher+　　  :' = '재부팅 · UMS 도구'

[sphaira]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Sphaira' = ' 유용한 기능 (앱 실행 상태)'

[manual]
;mode=table
;spacing=3
;gap=0
'앱 숨기기:' = '  숨기기  켬'
'바로가기 설치:' = '홈브류 +   바로가기 설치'
'' = ''

[manual]
;mode=table
;section_text_color=header
;info_text_color=notice
;spacing=0
;gap=0
'앱 설치' = ' NSPXCINSZXCZ'
'' = ''

[manual]
;mode=table
;section_text_color=accent
;info_text_color=accent
;spacing=0
;gap=0
'1.PC:' = '  기타  FTP·MTP 설치  파일 넣기'
'' = ''

[manual]
;mode=table
;spacing=3
;gap=0
'FTP:' = '서버 연결  Install 폴더에 파일 끌어넣기'
'MTP:' = 'PC 연결  Install 폴더에 파일 끌어넣기'
'' = ''

[manual]
;mode=table
;section_text_color=accent
;info_text_color=accent
;spacing=0
;gap=0
'2.외장하드:' = '파일 탐색기  마운트  파일 선택'
'' = ''

[manual]
;mode=table
;spacing=3
;gap=0
'HDD:' = '하드 연결  파일 탐색기    고급 '
'' = '마운트  하드 선택  파일 선택  예'

[@오류 코드]
[fatal_photoviewer]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'앨범 오류' = ' 010000000000100D'

[fatal_album]
;mode=table
;alignment=center
;offset=8
;spacing=4
'' = 'sphairahbmenu 혹은 dmnt의 구성 불량'
'' = '애플릿 모드 사용중인 경우, 메모리 부족 충돌'

[blank]
;mode=table
;background=false
;gap=24

[fatal_CPU]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'CPU 파손' = ' 524850534F53454D'

[cpu_dead]
;mode=table
;alignment=center
;offset=8
'' = 'CPU에 복구 불가능한 손상이 발생'

[blank]
;mode=table
;background=false
;gap=24

[fatal_ns_sys]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'시스템 오류' = ' Code: XXXX-XXXX'

[*시스템 오류]
;mode=forwarder
;mini=true
package_source './err_code.ini'

[blank]
;mode=table
;background=false
;gap=24

[fatal_frequent]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'모듈 오류' = ' 스위치 모듈 오류시 안내문 참고'

[fatal_ns_sm]
;mode=table
;spacing=4
;gap=25
'' = '앱이 아닌 스위치 모듈 오류가 발생한 경우'
'' = ''
'시스낸드:' = '시스템 파일 손상, 낸드 리빌딩 필요'
'에뮤낸드:' = '에뮤낸드 파일 손상, 재생성으로 해결'

[*자주 발생하는 오류]
;mode=forwarder
;mini=true
package_source './frequent_err.ini'

[*앱 모듈 오류]
;mode=forwarder
;mini=true
package_source './global_err.ini'

[*스위치 모듈 오류]
;mode=forwarder
;mini=true
package_source './module_err.ini'
