;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[@부트로더]
[boot]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'부팅' = ' 시작 관련 설정을 변경합니다'

[backlight]
;mode=table
;gap=24
'Hekate' = '홈 화면의 백라이트 밝기를 조절합니다'

[화면 밝기]
;mode=step_trackbar
;unlocked=false
;min_value=30
;max_value=220
;units=%
;steps=20
;on_every_tick=true
set-ini-val /bootloader/hekate_ipl.ini config backlight {value}

[blank]
;mode=table
;background=false
;gap=17

[autohosoff]
;mode=table
;gap=24
'시스템 종료 후' = '자동으로 깨어나지 않도록합니다'

[HOS 종료]
;mode=named_step_trackbar
;unlocked=false
json_file_source './json/auto_hos_off.json' label
set-ini-val '/bootloader/hekate_ipl.ini' config autohosoff {json_file_source(*,name)}

[blank]
;mode=table
;background=false
;gap=17

[bootwait]
;mode=table
;gap=24
'1초 이상:' = ' 볼륨 입력으로 Hekate로 이동 가능'

[부팅 화면 대기 시간]
;mode=step_trackbar
;unlocked=false
;min_value=0
;max_value=20
;units=초
set-ini-val /bootloader/hekate_ipl.ini config bootwait {value}

[blank]
;mode=table
;background=false
;gap=19

[autoboot]
;mode=table
;gap=24
' 버튼' = '재기동 시 Atmosphère로 재시작합니다'

[자동 부팅]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/hekate_ipl.ini' config autoboot 1
set-ini-val '/bootloader/hekate_ipl.ini' config autoboot_list 1
off:
set-ini-val '/bootloader/hekate_ipl.ini' config autoboot 0
set-ini-val '/bootloader/hekate_ipl.ini' config autoboot_list 0

[@시스템]
[시스템 설정]
[system_settings]
;mode=table
;gap=27
'atmosphère · usb' = ''

[dmnt 치트]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/system_settings.ini' atmosphere dmnt_cheats_enabled_by_default u8!0x1
off:
set-ini-val '/atmosphere/config/system_settings.ini' atmosphere dmnt_cheats_enabled_by_default u8!0x0

[dmnt 토글 저장]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/system_settings.ini' atmosphere dmnt_always_save_cheat_toggles u8!0x1
off:
set-ini-val '/atmosphere/config/system_settings.ini' atmosphere dmnt_always_save_cheat_toggles u8!0x0

[USB 3.0]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/system_settings.ini' usb usb30_force_enabled u8!0x1
off:
set-ini-val '/atmosphere/config/system_settings.ini' usb usb30_force_enabled u8!0x0

[blank]
;mode=table
;background=false
;gap=30

[nogc]
;mode=table
;spacing=10
;gap=-15
'stratoshère' = '게임 카드 설치를 비활성화합니다'
' ' = ''

[notice]
;mode=table
;background=false
;section_text_color=warning
;info_text_color=warning
;gap=27
'' = '슬립 해제시 카트리지를 인식하면 오류 발생'

[카트리지 차단]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/stratosphere.ini' stratosphere nogc 1
off:
set-ini-val '/atmosphere/config/stratosphere.ini' stratosphere nogc 0

[blank]
;mode=table
;background=false
;gap=30

[am]
;mode=table
;spacing=10
;gap=-15
'am.debug' = ' 버튼 녹화 설정을 변경합니다'
' ' = ''

[notice]
;mode=table
;background=false
;section_text_color=warning
;info_text_color=warning
;gap=27
'' = '값에 따라 녹화 시간이 변동될 수 있습니다'

[FPS]
;mode=named_step_trackbar
;unlocked=false
json_file_source './json/am_fps.json' label
set-ini-val '/atmosphere/config/system_settings.ini' am.debug continuous_recording_fps u32!{json_file_source(*,hex)}

[Bitrate]
;mode=named_step_trackbar
;unlocked=false
json_file_source './json/am_bitrate.json' label
set-ini-val '/atmosphere/config/system_settings.ini' am.debug continuous_recording_video_bit_rate u32!{json_file_source(*,hex)}

[Key frame]
;mode=named_step_trackbar
;unlocked=false
json_file_source './json/am_key_frame.json' label
set-ini-val '/atmosphere/config/system_settings.ini' am.debug continuous_recording_key_frame_count u32!{json_file_source(*,hex)}

[blank]
;mode=table
;background=false
;gap=30

[only_sys]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'시스낸드 전용' = ' 에뮤낸드 = 기본 적용'

[cal0_blank]
;mode=table
;gap=27
'exosphère' = '본체의 시리얼 넘버를 변조합니다'

[시리얼 변조]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/exosphere.ini' exosphere blank_prodinfo_sysmmc 1
off:
set-ini-val '/atmosphere/config/exosphere.ini' exosphere blank_prodinfo_sysmmc 0

[blank]
;mode=table
;background=false
;gap=30

[dns_mitm]
;mode=table
;gap=27
'dns.mitm' = '닌텐도 서버와 연결을 차단합니다'

[서버 차단]
;mode=toggle?off
;mini=true
on:
cp '/atmosphere/hosts/emummc.txt' '/atmosphere/hosts/sysmmc.txt'
off:
del '/atmosphere/hosts/sysmmc.txt'

[blank]
;mode=table
;background=false
;gap=30

[reset]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'설정 값 적용리셋' = ' 자동으로 재부팅 됩니다'

[설정 적용]
;mini=true
reboot ini CFW

[기본 값으로 되돌리기]
;mini=true
try:
set-ini-val /bootloader/hekate_ipl.ini config backlight 80
set-ini-val /bootloader/hekate_ipl.ini config bootwait 1
set-ini-val /bootloader/hekate_ipl.ini config autoboot 0
set-ini-val /bootloader/hekate_ipl.ini config autoboot_list 0
set-ini-val /bootloader/hekate_ipl.ini config autohosoff 2
set-ini-val /atmosphere/config/system_settings.ini eupld upload_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini usb usb30_force_enabled u8!0x1
set-ini-val /atmosphere/config/system_settings.ini ro ease_nro_restriction u8!0x1
set-ini-val /atmosphere/config/system_settings.ini lm enable_sd_card_logging u8!0x0
set-ini-val /atmosphere/config/system_settings.ini erpt disable_automatic_report_cleanup u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere fatal_auto_reboot_interval u64!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere power_menu_reboot_function str!payload
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_cheats_enabled_by_default u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere dmnt_always_save_cheat_toggles u8!0x1
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_hbl_bis_write u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_hbl_cal_read u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere fsmitm_redirect_saves_to_sd u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_am_debug_mode u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_dns_mitm u8!0x1
set-ini-val /atmosphere/config/system_settings.ini atmosphere add_defaults_to_dns_hosts u8!0x1
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_dns_mitm_debug_log u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_htc u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_log_manager u8!0x0
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x1
set-ini-val /atmosphere/config/system_settings.ini hbloader applet_heap_size u64!0x0
set-ini-val /atmosphere/config/system_settings.ini hbloader applet_heap_reservation_size u64!0x8600000
set-ini-val /atmosphere/config/system_settings.ini contents_delivery enable_debug_api u8!0x1
set-ini-val /atmosphere/config/system_settings.ini psm enough_power_threshold_mw u32!0x3E80
set-ini-val /atmosphere/config/system_settings.ini am.debug continuous_recording_fps u32!30
set-ini-val /atmosphere/config/system_settings.ini am.debug continuous_recording_video_bit_rate u32!0x4C4B40
set-ini-val /atmosphere/config/system_settings.ini am.debug continuous_recording_key_frame_count u32!15
set-ini-val /atmosphere/config/system_settings.ini bgtc enable_halfawake u32!0x0
set-ini-val /atmosphere/config/system_settings.ini bgtc minimum_interval_normal u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini bgtc minimum_interval_save u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini bgtc battery_threshold_save u32!0x64
set-ini-val /atmosphere/config/system_settings.ini bgtc battery_threshold_stop u32!0x64
set-ini-val /atmosphere/config/system_settings.ini npns background_processing u8!0x0
set-ini-val /atmosphere/config/system_settings.ini npns sleep_periodic_interval u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini npns sleep_processing_timeout u32!0x0
set-ini-val /atmosphere/config/system_settings.ini npns sleep_max_try_count u32!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_download_task_list u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_download_ticket u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_network_update u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_random_wait u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_request_on_cold_boot u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_send_rights_usage_status_request u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_sync_elicense_request u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification enable_version_list u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ns.notification retry_interval_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ns.notification retry_interval_max u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ns.notification version_list_waiting_limit_bias u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ns.notification version_list_waiting_limit_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini account na_required_for_network_service u8!0x0
set-ini-val /atmosphere/config/system_settings.ini account na_license_verification_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini account.daemon background_awaking_periodicity u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini account.daemon initial_schedule_delay u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini account.daemon profile_sync_interval u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini account.daemon na_info_refresh_interval u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini capsrv enable_album_screenshot_filedata_verification u8!0x0
set-ini-val /atmosphere/config/system_settings.ini capsrv enable_album_movie_filehash_verification u8!0x0
set-ini-val /atmosphere/config/system_settings.ini capsrv enable_album_movie_filesign_verification u8!0x0
set-ini-val /atmosphere/config/system_settings.ini friends background_processing u8!0x0
set-ini-val /atmosphere/config/system_settings.ini notification.presenter snooze_interval_in_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini notification.presenter connection_retry_count u32!0x0
set-ini-val /atmosphere/config/system_settings.ini notification.presenter alarm_pattern_total_repeat_count u32!0x0
set-ini-val /atmosphere/config/system_settings.ini notification.presenter alarm_pattern_with_vibration_repeat_count u32!0x0
set-ini-val /atmosphere/config/system_settings.ini prepo transmission_interval_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo transmission_retry_interval_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo transmission_retry_interval_max u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo transmission_interval_in_sleep u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo statistics_save_interval_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo statistics_post_interval u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini prepo save_system_report u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc default_auto_upload_global_setting u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc default_auto_download_global_setting u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc autonomy_registration_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc network_service_license_info_cache_expiration_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc postponed_transfer_task_processing_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc retry_offset_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc network_trouble_detection_span_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc network_connection_polling_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini olsc is_save_data_backup_policy_check_required u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc is_global_transfer_task_autonomy_registration_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc is_on_event_transfer_task_registration_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini olsc is_periodic_transfer_task_registration_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ntc is_autonomic_correction_enabled u8!0x0
set-ini-val /atmosphere/config/system_settings.ini ntc autonomic_correction_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ntc autonomic_correction_failed_retry_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ntc autonomic_correction_immediate_try_count_max u32!0x0
set-ini-val /atmosphere/config/system_settings.ini ntc autonomic_correction_immediate_try_interval_milliseconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini systemupdate bgnup_retry_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini ns.rights skip_account_validation_on_rights_check u8!0x1
set-ini-val /atmosphere/config/system_settings.ini ns.rights next_available_time_of_unexpected_error u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini pctl intermittent_task_interval_seconds u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini sprofile adjust_polling_interval_by_profile u8!0x0
set-ini-val /atmosphere/config/system_settings.ini sprofile polling_interval_sec_max u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini sprofile polling_interval_sec_min u32!0x7FFFFFFF
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
set-ini-val /atmosphere/config/system_settings.ini tc use_configurations_on_fwdbg u8!0x1
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, 54000, 128, 255], [54000, 1000000, 255, 255]]"
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, 54000, 128, 255], [54000, 1000000, 255, 255]]"
set-ini-val /atmosphere/config/system_settings.ini tc holdable_tskin u32!0xEA60
set-ini-val /atmosphere/config/system_settings.ini tc touchable_tskin u32!0xEA60
set-ini-val '/atmosphere/config/stratosphere.ini' stratosphere nogc 0
set-ini-val '/atmosphere/config/exosphere.ini' exosphere blank_prodinfo_sysmmc 0
del ./config.ini
del '/atmosphere/hosts/sysmmc.txt'
refresh
reboot ini CFW
