;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[@]
[launcher]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Moon 런처' = ' AtmosphèreL4T 부팅 엔트리'

[notice]
;mode=table
;spacing=3
;gap=0
;info_text_color=accent
'' = '각 엔트리의 아이콘은 자동으로 설정됩니다'
'' = ''

[warning]
;mode=table
;spacing=3
;gap=0
;section_text_color=warning
;info_text_color=warning
'' = 'L4T를 부팅하려면 OS의 설치가 필요합니다'
'' = 'Ubuntu의 경우, 버전을 맞춰 생성하세요'
'' = ''

[entries]
;mode=table
;spacing=5
;gap=25
'CFW:' = '기본 낸드로 설정된 커펌 (자동 생성)'
'Stock:' = '커펌 모듈 OFF 정펌 (자동 생성)'
'Android:' = '안드로이드 (Lineage OS) 부팅 엔트리'
'Emulator:' = 'Libretro 기반 Lakka 부팅 엔트리'
'Ubuntu:' = 'Switchroot 포팅 LINUX 부팅 엔트리'

[CFW]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ams_cfw.ini' 'CFW'
set-ini-val '/bootloader/ini/ams_cfw.ini' 'CFW' payload bootloader/payloads/fusee.bin
set-ini-val '/bootloader/ini/ams_cfw.ini' 'CFW' logopath bootloader/res/asap.bmp
off:
del '/bootloader/ini/ams_cfw.ini'

[Stock]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ams_wbfix.ini' 'Stock'
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' fss0 atmosphere/package3
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' stock 1
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' emummc_force_disable 1
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' logopath bootloader/res/asap.bmp
off:
del '/bootloader/ini/ams_wbfix.ini'

[Android]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/ini/android.ini' 'Android' l4t 1
set-ini-val '/bootloader/ini/android.ini' 'Android' emmc 0
set-ini-val '/bootloader/ini/android.ini' 'Android' boot_prefixes switchroot/android/
set-ini-val '/bootloader/ini/android.ini' 'Android' id SWANDR
set-ini-val '/bootloader/ini/android.ini' 'Android' r2p_action self
set-ini-val '/bootloader/ini/android.ini' 'Android' usb3_enable 1
set-ini-val '/bootloader/ini/android.ini' 'Android' oc 0
set-ini-val '/bootloader/ini/android.ini' 'Android' logopath switchroot/android/android.bmp
off:
del '/bootloader/ini/android.ini'

[Emulator]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' l4t 1
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' boot_prefixes lakka/boot/
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' id SWR-LAK
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' icon bootloader/res/icon/lakka_nobox.bmp
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' logopath lakka/boot/lakka.bmp
off:
del '/bootloader/ini/lakka.ini'

[Ubuntu Bionic]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ubuntu.ini' 'Ubuntu'
set-ini-val './config.ini' 'Ubuntu Jammy' footer Off
set-ini-val './config.ini' 'Ubuntu Noble' footer Off
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' l4t 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' emmc 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' boot_prefixes /switchroot/ubuntu/
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' uart_port 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' id SWR-UBU
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' r2p_action self
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' usb3_enable 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' logopath switchroot/ubuntu-jammy/res/jammy.bmp
refresh
off:
del '/bootloader/ini/ubuntu.ini'

[Ubuntu Jammy]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ubuntu.ini' 'Ubuntu'
set-ini-val './config.ini' 'Ubuntu Bionic' footer Off
set-ini-val './config.ini' 'Ubuntu Noble' footer Off
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' l4t 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' emmc 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' boot_prefixes /switchroot/ubuntu-jammy/
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' uart_port 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' id SWR-JAM
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' r2p_action self
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' usb3_enable 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' logopath switchroot/ubuntu/res/bionic.bmp
refresh
off:
del '/bootloader/ini/ubuntu.ini'

[Ubuntu Noble]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ubuntu.ini' 'Ubuntu'
set-ini-val './config.ini' 'Ubuntu Bionic' footer Off
set-ini-val './config.ini' 'Ubuntu Jammy' footer Off
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' l4t 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' emmc 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' boot_prefixes /switchroot/ubuntu-noble/
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' uart_port 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' id SWR-NOB
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' r2p_action self
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' usb3_enable 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' logopath switchroot/ubuntu-noble/res/noble.bmp
refresh
off:
del '/bootloader/ini/ubuntu.ini'
