;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[@]
[launcher]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Moon 런처' = ' AtmosphèreL4T 부팅 엔트리'

[notice]
;mode=table
;spacing=3
;gap=-153
;info_text_color=accent
'' = '각 엔트리의 아이콘은 자동으로 설정됩니다'
' ' = ''
' ' = ''
' ' = ''
' ' = ''
' ' = ''
' ' = ''
' ' = ''
' ' = ''
' ' = ''

[warning]
;mode=table
;background=false
;spacing=3
;gap=18
;section_text_color=warning
;info_text_color=warning
'' = 'L4T를 부팅하려면 OS의 설치가 필요합니다'
'' = 'Ubuntu의 경우, 버전을 맞춰 생성하세요'

[entries]
;mode=table
;background=false
;spacing=5
;gap=27
'CFW:' = '기본 낸드로 설정된 커펌 (자동 생성)'
'Stock:' = '커펌 모듈 OFF 정펌 (자동 생성)'
'Emulator:' = 'Libretro 기반 Lakka 부팅 엔트리'
'Android:' = '안드로이드 (Lineage OS) 부팅 엔트리'
'Ubuntu:' = 'Switchroot 포팅 LINUX 부팅 엔트리'

[custom_firmware]
;mode=table
;background=false
;header_indent=true
;info_text_color=header
'Atmosphère' = ''

[CFW]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ams_cfw.ini' 'CFW'
set-ini-val '/bootloader/ini/ams_cfw.ini' 'CFW' payload bootloader/payloads/fusee.bin
set-ini-val '/bootloader/ini/ams_cfw.ini' 'CFW' logopath bootloader/res/asap.bmp
off:
del '/bootloader/ini/ams_cfw.ini'

[Stock]
;mode=toggle
;mini=true
on:
remove-ini-section '/bootloader/ini/ams_wbfix.ini' 'Stock'
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' fss0 atmosphere/package3
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' stock 1
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' emummc_force_disable 1
set-ini-val '/bootloader/ini/ams_wbfix.ini' 'Stock' logopath bootloader/res/asap.bmp
off:
del '/bootloader/ini/ams_wbfix.ini'

[blank]
;mode=table
;background=false
;gap=20

[linux_for_tegra]
;mode=table
;background=false
;header_indent=true
;info_text_color=header
'Linux for Tegra' = ''

[Emulator]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' l4t 1
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' boot_prefixes lakka/boot/
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' id SWR-LAK
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' icon bootloader/res/icon/lakka_nobox.bmp
set-ini-val '/bootloader/ini/lakka.ini' 'Lakka' logopath lakka/boot/lakka.bmp
off:
del '/bootloader/ini/lakka.ini'

[*Android]
;mini=true
[notice]
;mode=table
;spacing=3
;gap=30
;info_text_color=accent
ini_file './config.ini'
'' = 'L4T 런처의 세부 설정을 조정합니다'
' '=''
'런처 생성/제거:' = 'Android 기본 값을 생성/제거'
'설치 경로:' = 'OS가 설치된 낸드를 설정'
'재부팅 옵션:' = '재부팅 부트로더를 선택'
'USB 3.0:' = 'USB 3.0 지원 유무 설정'
'DDR200:' = '삼성 SD 카드인 경우에만 활성화'
'RAM OC:' = '잘 모르는 경우 설정하지 마세요'

[런처 생성/제거?Android]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/ini/android.ini' 'Android' l4t 1
set-ini-val '/bootloader/ini/android.ini' 'Android' emmc 0
set-ini-val '/bootloader/ini/android.ini' 'Android' boot_prefixes switchroot/android/
set-ini-val '/bootloader/ini/android.ini' 'Android' id SWANDR
set-ini-val '/bootloader/ini/android.ini' 'Android' r2p_action self
set-ini-val '/bootloader/ini/android.ini' 'Android' usb3_enable 0
set-ini-val '/bootloader/ini/android.ini' 'Android' ddr200_enable 0
set-ini-val '/bootloader/ini/android.ini' 'Android' ram_oc 0
set-ini-val '/bootloader/ini/android.ini' 'Android' logopath switchroot/android/android.bmp
refresh
off:
remove-ini-section './config.ini' '*설치 경로?Android'
remove-ini-section './config.ini' '*재부팅 옵션?Android'
remove-ini-section './config.ini' '*USB 3.0?Android'
remove-ini-section './config.ini' '*DDR200'
remove-ini-section './config.ini' '*RAM OC?Android'
remove-ini-section './config.ini' '*RAM VDD2?Android'
remove-ini-section './config.ini' '*RAM VDDQ?Android'
del '/bootloader/ini/android.ini'
refresh

[*설치 경로?Android]
;mode=option
;mini=true
json_file_source './json/install_nand.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' emmc {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*재부팅 옵션?Android]
;mode=option
;mini=true
json_file_source './json/l4t_reboot.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' r2p_action {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*USB 3.0?Android]
;mode=option
;mini=true
json_file_source './json/enable.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' usb3_enable {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*DDR200]
;mode=option
;mini=true
json_file_source './json/enable.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' ddr200_enable {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*RAM OC?Android]
;mode=option
;mini=true
erista:
json_file_source './json/ram_oc_erista.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' ram_oc {json_file_source(*,val)}
set-footer '{json_file_source(*,lbl)}'
mariko:
json_file_source './json/ram_oc_mariko.json' label
set-ini-val '/bootloader/ini/android.ini' 'Android' ram_oc {json_file_source(*,val)}
set-footer '{json_file_source(*,lbl)}'
exec LauncherSettings

[*RAM VDD2?Android]
;mode=step_trackbar
;unlocked=false
;min_value=1100
;max_value=1175
;units=mV
set-ini-val '/bootloader/ini/android.ini' 'Android' ram_oc_vdd2 {value}

[*RAM VDDQ?Android]
;system=mariko
;mode=step_trackbar
;unlocked=false
;min_value=600
;max_value=650
;units=mV
set-ini-val '/bootloader/ini/android.ini' 'Android' ram_oc_vddq {value}


[*Ubuntu]
;mini=true
[notice]
;mode=table
;spacing=3
;gap=30
;info_text_color=accent
ini_file './config.ini'
'' = 'L4T 런처의 세부 설정을 조정합니다'
' '=''
'런처 생성/제거:' = 'Ubuntu 기본 값을 생성/제거'
'설치 버전:' = '설치한 Ubuntu 버전을 반드시 지정'
'설치 경로:' = 'OS가 설치된 낸드를 설정'
'재부팅 옵션:' = '재부팅 부트로더를 선택'
'USB 3.0:' = 'USB 3.0 지원 유무 설정'
'RAM OC:' = '잘 모르는 경우 설정하지 마세요'

[런처 생성/제거?Ubuntu]
;mode=toggle
;mini=true
on:
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' l4t 1
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' emmc 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' uart_port 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' id SWR-UBU
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' r2p_action self
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' usb3_enable 0
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc 0
refresh
off:
remove-ini-section './config.ini' '*설치 버전?Ubuntu'
remove-ini-section './config.ini' '*설치 경로?Ubuntu'
remove-ini-section './config.ini' '*재부팅 옵션?Ubuntu'
remove-ini-section './config.ini' '*USB 3.0?Ubuntu'
remove-ini-section './config.ini' '*RAM OC?Ubuntu'
remove-ini-section './config.ini' '*RAM VDD2?Erista'
remove-ini-section './config.ini' '*RAM VDD2?Mariko'
remove-ini-section './config.ini' '*RAM VDDQ?Ubuntu'
del '/bootloader/ini/ubuntu.ini'
refresh

[*설치 버전?Ubuntu]
;mode=option
;mini=true
json_file_source './json/ubuntu_version.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' boot_prefixes /switchroot/{json_file_source(*,path)}/
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' id {json_file_source(*,id)}
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' logopath switchroot/{json_file_source(*,path)}/res/ubuntu.bmp
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*설치 경로?Ubuntu]
;mode=option
;mini=true
json_file_source './json/install_nand.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' emmc {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*재부팅 옵션?Ubuntu]
;mode=option
;mini=true
json_file_source './json/l4t_reboot.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' r2p_action {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*USB 3.0?Ubuntu]
;mode=option
;mini=true
json_file_source './json/enable.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' usb3_enable {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'
exec LauncherSettings

[*RAM OC?Ubuntu]
;mode=option
;mini=true
erista:
json_file_source './json/ram_oc_erista.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc {json_file_source(*,val)}
set-footer '{json_file_source(*,lbl)}'
mariko:
json_file_source './json/ram_oc_mariko.json' label
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc {json_file_source(*,val)}
set-footer '{json_file_source(*,lbl)}'
exec LauncherSettings

[*RAM VDD2?Erista]
;system=erista
;mode=step_trackbar
;unlocked=false
;min_value=1050
;max_value=1237
;units=mV
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc_vdd2 {value}

[*RAM VDD2?Mariko]
;system=mariko
;mode=step_trackbar
;unlocked=false
;min_value=1050
;max_value=1175
;units=mV
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc_vdd2 {value}

[*RAM VDDQ?Ubuntu]
;system=mariko
;mode=step_trackbar
;unlocked=false
;min_value=550
;max_value=650
;units=mV
set-ini-val '/bootloader/ini/ubuntu.ini' 'Ubuntu' ram_oc_vddq {value}
