;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[@]
[cfw]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Custom Firmware' = ' 시스템 세부 설정 편집'

[info]
;mode=table
;alignment=right
;spacing=0
;gap=0
;info_text_color=accent
'' = '커스텀 펌웨어의 여러 기능을 설정합니다'
'' = ''

[info]
;mode=table
;alignment=right
;spacing=3
;gap=25
'기본 낸드:' = 'Atmosphère 부팅 낸드 설정'
'부팅 런처:' = 'Hekate - Moon 런처 항목 설정'
'시스템 설정:' = '커펌 시스템 값 설정'
'홈브류 설정:' = 'Sphaira 실행 버튼 설정'
'SD 카드 정리:' = 'Ultrahand 초기화, 정크 삭제'

[*기본 낸드]
;mode=option
;mini=true
json_file_source './json/default_nand.json' label
set-ini-val '/emummc/emummc.ini' emummc enabled {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'

[*부팅 런처]
;mode=forwarder
;mini=true
package_source './moon_launcher.ini'

[*시스템 설정]
;mode=forwarder
;mini=true
exec SystemSettings
package_source './cfw_settings.ini'

[*홈브류 설정]
;mode=forwarder
;mini=true
exec SystemSettings
package_source './sphaira.ini'

[SD 카드 정리]
;mini=true
try:
set-ini-val '/config/ultrahand/overlays.ini' 'emuiibo.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'FPSLocker.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'NX-FanControl.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'ovlEdiZon.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'ovlmenu.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'ovlSysmodules.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'ReverseNX-RT-ovl.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'Status-Monitor-Overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'sys-clk-overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/overlays.ini' 'sys-patch-overlay.ovl' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'Extra Setting+' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'System Clock+' hide 'false'
set-ini-val '/config/ultrahand/packages.ini' 'OC Toolkit' hide 'true'
set-ini-val '/config/ultrahand/packages.ini' 'EOS Toolkit' custom_name 'OC Toolkit'
set-ini-val '/config/ultrahand/packages.ini' 'SC Toolkit' custom_name 'OC Toolkit'
set-ini-val 'switch/.packages/System Clock+/config.ini' 'EOS Toolkit' footer ''
set-ini-val 'switch/.packages/System Clock+/config.ini' 'SC Toolkit' footer ''
rename '/atmosphere/contents/420000000000000B/' '/atmosphere/contents/420000000000000B_/'
del '/atmosphere/crash_reports/'
del '/atmosphere/erpt_reports/'
del '/atmosphere/erpt_reports'
del '/atmosphere/fatal_errors/'
del '/atmosphere/fatal_reports/'
del '/atmosphere/update/'
del '/atmosphere/logs/sys-patch.log'
del '/atmosphere/kips/loader.kip'
del '/bootloader/debug/'
del '/Firmware/'
del '/switch/.packages/OC Toolkit/erista/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/erista/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/cpu_voltages.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_uv3.json'
del '/switch/.packages/OC Toolkit/mariko/gpu_vmax.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vdd2.json'
del '/switch/.packages/OC Toolkit/mariko/ram_vddq.json'
del '/switch/.packages/OC Toolkit/backup_info.ini'
del '/switch/.packages/OC Toolkit/custom_table.ini'
del '/switch/.packages/OC Toolkit/info.ini'
del '/switch/.packages/OC Toolkit/update.ini'
del '/config/ultrahand/sys-clk.ini'
del '/switch/sphaira/cache/'
del '/SAFE/'
del '/SYSTEM/'
del '/USER/'
del '/BCPKG2-1-Normal-Main'
del '/BCPKG2-1-Normal-Main.bin'
del '/BCPKG2-2-Normal-Sub'
del '/BCPKG2-2-Normal-Sub.bin'
del '/BCPKG2-3-SafeMode-Main'
del '/BCPKG2-3-SafeMode-Main.bin'
del '/BCPKG2-4-SafeMode-Sub'
del '/BCPKG2-4-SafeMode-Sub.bin'
del '/BCPKG2-5-Repair-Main'
del '/BCPKG2-5-Repair-Main.bin'
del '/BCPKG2-6-Repair-Sub'
del '/BCPKG2-6-Repair-Sub.bin'
del '/boot.bis'
del '/BOOT0.bin'
del '/BOOT1.bin'
del '/payload.bin.aio'
del '/tinfoil.install.log'
del '/firmware.bin'
del '/update.bin'
del '/sdloader.enc'
del '/.dropbox.device'
del '/.Trash-1000/'
del '/.Trash-1000'
mkdir '/atmosphere/crash_reports/'
mkdir '/atmosphere/erpt_reports/'
mkdir '/atmosphere/fatal_errors/'
mkdir '/atmosphere/fatal_reports/'
set-footer '{timestamp("%Y-%m-%d")}'

[blank]
;mode=table
;background=false
;gap=30

[ram_expansion]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'RAM' = ' : 일반 기기: 8GB 기기'

[info]
;mode=table
;alignment=right
;section_text_color=warning
;info_text_color=warning
;gap=25
'' = '패치시 일반 기기는 작동하지 않게됩니다'

[8GB 패치]
;mode=toggle
;mini=true
on:
rename '/atmosphere/config/exosphere_.bin' '/atmosphere/config/exosphere.bin'
rename '/config/ultrahand/ram_4gb.ini' '/config/ultrahand/ram_8gb.ini'
del '/atmosphere/reboot_payload.bin'
del '/bootloader/payloads/fusee.bin'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee_8gb.bin' '/atmosphere/reboot_payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee_8gb.bin' '/bootloader/payloads/fusee.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_8gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_8gb.bin' '/payload.bin'
off:
rename '/atmosphere/config/exosphere.bin' '/atmosphere/config/exosphere_.bin'
rename '/config/ultrahand/ram_8gb.ini' '/config/ultrahand/ram_4gb.ini'
del '/atmosphere/reboot_payload.bin'
del '/bootloader/payloads/fusee.bin'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee_4gb.bin' '/atmosphere/reboot_payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee_4gb.bin' '/bootloader/payloads/fusee.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/payload.bin'
