;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[@]
[cfw]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'Custom Firmware' = ' 시스템 세부 설정 편집'

[info]
;mode=table
;alignment=right
;spacing=0
;gap=0
;info_text_color=accent
'' = '커스텀 펌웨어의 여러 기능을 설정합니다'
' ' = ''

[info]
;mode=table
;alignment=right
;spacing=2
;gap=20
'기본 낸드:' = 'Atmosphère 부팅 낸드 설정'
'부팅 런처:' = 'Hekate - Moon 런처 항목 설정'
'시스템 설정:' = '커펌 시스템 값 설정'
'홈브류 설정:' = 'Sphaira 실행 버튼 설정'
'SD 카드 정리:' = 'Ultrahand 초기화, 정크 삭제'

[*기본 낸드]
;mode=option
;mini=true
json_file_source './json/default_nand.json' label
set-ini-val '/emummc/emummc.ini' emummc enabled {json_file_source(*,name)}
set-footer '{json_file_source(*,label)}'

[*부팅 런처]
;mode=forwarder
;mini=true
package_source './moon_launcher.ini'

[*시스템 설정]
;mode=forwarder
;mini=true
exec SystemSettings
package_source './cfw_settings.ini'

[*홈브류 설정]
;mode=forwarder
;mini=true
exec SystemSettings
package_source './sphaira.ini'

[SD 카드 정리]
;mini=true
try:
del '/atmosphere/crash_reports/'
del '/atmosphere/erpt_reports/'
del '/atmosphere/erpt_reports'
del '/atmosphere/fatal_errors/'
del '/atmosphere/fatal_reports/'
del '/atmosphere/update/'
del '/atmosphere/logs/sys-patch.log'
del '/atmosphere/kips/loader.kip'
del '/bootloader/debug/'
del '/Firmware/'
del '/config/ultrahand/sys-clk.ini'
del '/switch/sphaira/cache/'
del '/SAFE/'
del '/SYSTEM/'
del '/USER/'
del '/BCPKG2-1-Normal-Main'
del '/BCPKG2-1-Normal-Main.bin'
del '/BCPKG2-2-Normal-Sub'
del '/BCPKG2-2-Normal-Sub.bin'
del '/BCPKG2-3-SafeMode-Main'
del '/BCPKG2-3-SafeMode-Main.bin'
del '/BCPKG2-4-SafeMode-Sub'
del '/BCPKG2-4-SafeMode-Sub.bin'
del '/BCPKG2-5-Repair-Main'
del '/BCPKG2-5-Repair-Main.bin'
del '/BCPKG2-6-Repair-Sub'
del '/BCPKG2-6-Repair-Sub.bin'
del '/boot.bis'
del '/BOOT0.bin'
del '/BOOT1.bin'
del '/payload.bin.aio'
del '/tinfoil.install.log'
del '/firmware.bin'
del '/update.bin'
del '/sdloader.enc'
del '/.dropbox.device'
del '/.Trash-1000/'
del '/.Trash-1000'
mkdir '/atmosphere/crash_reports/'
mkdir '/atmosphere/erpt_reports/'
mkdir '/atmosphere/fatal_errors/'
mkdir '/atmosphere/fatal_reports/'
set-footer '{timestamp("%Y-%m-%d")}'

[blank]
;mode=table
;background=false
;gap=13

[ram_expansion]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'RAM' = ' 40MB Memory8GB RAM'

[info]
;mode=table
;alignment=right
;section_text_color=warning
;info_text_color=warning
;gap=20
'' = '8GB 패치는 8GB RAM 설치 기기 전용입니다'

[40MB Memory 패치]
;mode=toggle
;mini=true
on:
rename '/config/ultrahand/ram_8gb.ini' '/config/ultrahand/ram_4gb.ini'
set-ini-val '/config/ultrahand/ram_4gb.ini' 'config' 40mb '1'
set-ini-val '/atmosphere/config/exosphere.ini' 'exosphere' enable_mem_mode '0'
del '/atmosphere/reboot_payload.bin'
del '/bootloader/payloads/fusee.bin'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/package3_40mb' '/atmosphere/package3.aio'
cp '/switch/.packages/.offload/ram_expansion/stratosphere_40mb.romfs' '/atmosphere/stratosphere.romfs.aio'
cp '/switch/.packages/.offload/ram_expansion/fusee_40mb.bin' '/atmosphere/reboot_payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee_40mb.bin' '/bootloader/payloads/fusee.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/payload.bin'
reboot
off:
rename '/config/ultrahand/ram_8gb.ini' '/config/ultrahand/ram_4gb.ini'
set-ini-val '/config/ultrahand/ram_4gb.ini' 'config' 40mb '0'
del '/atmosphere/reboot_payload.bin'
del '/bootloader/payloads/fusee.bin'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/package3' '/atmosphere/package3.aio'
cp '/switch/.packages/.offload/ram_expansion/stratosphere.romfs' '/atmosphere/stratosphere.romfs.aio'
cp '/switch/.packages/.offload/ram_expansion/fusee.bin' '/atmosphere/reboot_payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee.bin' '/bootloader/payloads/fusee.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/payload.bin'
reboot

[8GB RAM 패치]
;mode=toggle
;mini=true
on:
rename '/config/ultrahand/ram_4gb.ini' '/config/ultrahand/ram_8gb.ini'
set-ini-val '/atmosphere/config/exosphere.ini' 'exosphere' enable_mem_mode '1'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_8gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_8gb.bin' '/payload.bin'
reboot
off:
rename '/config/ultrahand/ram_8gb.ini' '/config/ultrahand/ram_4gb.ini'
set-ini-val '/config/ultrahand/ram_4gb.ini' 'config' 40mb '0'
set-ini-val '/atmosphere/config/exosphere.ini' 'exosphere' enable_mem_mode '0'
del '/atmosphere/reboot_payload.bin'
del '/bootloader/payloads/fusee.bin'
del '/bootloader/update.bin'
del '/payload.bin'
cp '/switch/.packages/.offload/ram_expansion/package3' '/atmosphere/package3.aio'
cp '/switch/.packages/.offload/ram_expansion/stratosphere.romfs' '/atmosphere/stratosphere.romfs.aio'
cp '/switch/.packages/.offload/ram_expansion/fusee.bin' '/atmosphere/reboot_payload.bin'
cp '/switch/.packages/.offload/ram_expansion/fusee.bin' '/bootloader/payloads/fusee.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/bootloader/update.bin'
cp '/switch/.packages/.offload/ram_expansion/hekate_4gb.bin' '/payload.bin'
reboot
