;override=커스텀 펌웨어 관련 설정을 진행합니다
;creator=Asa

[홈브류 설정 (sphaira)]
[full]
;mode=table
;spacing=0
;gap=0
;info_text_color=notice
'풀 메모리 모드' = ' 메모리 제한 없음'
'' = ''

[full]
;mode=table
;spacing=5
;gap=0
;info_text_color=accent
'권장:' = 'sphaira 열기  sphaira 아이콘으로 이동'
'' = '  버튼 입력  바로가기 설치  설치'
'' = ''

[info]
;mode=table
;gap=27
'' = '(타이틀) +  홀드 진입을 활성화합니다'

[활성화]
;mode=toggle
;mini=true
on:
set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_any_app true
off:
set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_any_app false

[blank]
;mode=table
;background=false
;gap=30

[applet]
;mode=table
;spacing=0
;gap=0
;section_text_color=warning
;info_text_color=notice
'애플릿 모드' = ' 메모리 제한됨'
'' = ''

[notice]
;mode=table
;spacing=0
;gap=0
'' = ' (앨범),  (유저) 진입 설정을 변경합니다'
'' = ''

[info]
;mode=table
;gap=27
;info_text_color=accent
'' = '기본:  (앨범) +  홀드'

[*진입 아이콘]
;mode=option
;mini=true
json_file_source './json/hb_applet_icon.json' icon
set-ini-val '/atmosphere/config/override_config.ini' hbl_config program_id_0 {json_file_source(*,id)}
set-footer '{json_file_source(*,icon)}'

[*진입 커맨드]
;mode=option
;mini=true
json_file_source './json/hb_applet_override.json' label
set-ini-val '/atmosphere/config/override_config.ini' hbl_config override_key {json_file_source(*,key)}
set-footer '{json_file_source(*,label)}'

[blank]
;mode=table
;background=false
;gap=30

[lang_patch]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'언어 패치' = ' Sphaira 번역 업데이트'

[한글 패치]
;mini=true
try:
del '/config/sphaira/i18n/ko.json'
download https://raw.githubusercontent.com/Yorunokyujitsu/ASAP-NX/main/misc/json/lang/sphaira/ko.json /config/sphaira/i18n/ko.json