;override=OC Switchcraft EOS
;creator=Asa
;color=red

[@설정 가이드]
[cpu_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'CPU 오버클럭' = ' speedo: {cpu_speedo}IDDQ: {cpu_iddq}'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
'1. CPU 최대 클럭 설정' = ''
'' = '시트 정보를 참고하여 허용 클럭 확인'
'' = '시스템 설정  CPU 최대 주파수  클럭 선택'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=0
'2. 부스트 클럭 설정' = ''
'' = '시스템 설정  부스트 모드  를  로 전환'
'' = ' 부스트 클럭  권장/기본/희망 클럭 선택'
' ' = ''

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
;section_text_color=warning
' 자동 설정을 희망하는 경우' = ''
'' = '시스템 설정  CPU 자동 부스트  를  전환'

[manual]
;mode=table
;alignment=left
;offset=20
;spacing=4
;gap=27
'3. 언더볼트 레벨 설정' = ''
erista:
'' = '- 1-5 내에서 안정적인 최대값 사용'
'' = '- 1-2 이하 부스트 클럭: 1785 MHz'
'' = '- 　3 이상 부스트 클럭: 2091 MHz'
mariko:
'' = '- 1-4 내에서 안정적이면 5-8 사이 안정값 사용'
'' = '- 1-5 이하 부스트 클럭:　               2400 MHz'
'' = '- 　6 이상, 1650 이상 부스트 클럭: 2600 MHz'

[manual]
;mode=table
;alignment=left
;offset=28
;spacing=4
;gap=27
erista:
'4. 전압 설정' = ''
'' = '최소 전압: 800-850 mV 내에서 설정'
'' = '전압 제한: 1225-1257 mV 내에서 설정'
mariko:
'4. 고주파 언더볼트 및 테이블 설정' = ''
'' = '6-10 내에서 안정적인 값 사용 (일부 11-12)'
'' = '자동 혹은 기본 테이블 사용 권장'

[manual]
;mode=table
;alignment=left
;offset=25
;spacing=4
erista:
'5. 설정 저장 및 적용' = ''
'' = '시스템 백업  Slot  분류 선택  백업'
'' = ' Launcher+  에뮤/시스낸드 (커펌)  재부팅'
mariko:
'5. 전압 설정' = ''
'' = '저주파 최소 전압: 590-620 mV 내에서 설정'
'' = '고주파 최소 전압: 720-750 mV 내에서 설정'
'' = '전압 제한: 1120-1160 mV 내에서 설정'

[@추가 정보]
[cpu_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'CPU 오버클럭' = ' speedo: {cpu_speedo}IDDQ: {cpu_iddq}'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
erista:
'6. 동작 확인 (게임 실행)' = ''
'' = 'Ultrahand  오버레이  Sys-Clk-EOS'
'' = ' 프로필 편집  CPU  설정 클럭 선택'
mariko:
'6. 설정 저장 및 적용' = ''
'' = '시스템 백업  Slot  분류 선택  백업'
'' = ' Launcher+  에뮤/시스낸드 (커펌)  재부팅'

[manual]
;system=mariko
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=40
'7. 동작 확인 (게임 실행)' = ''
'' = 'Ultrahand  오버레이  Sys-Clk-EOS'
'' = ' 프로필 편집  CPU  설정 클럭 선택'

[err]
;mode=table
;background=false
;header_indent=true
;info_text_color=accent
;section_text_color=header
'오류 발생시' = ''

[manual]
;mode=table
;alignment=left
;offset=20
;spacing=4
'안정 값이 아닌 경우, 발생하는 오류' = ''
'' = '- 화면이 깨지거나 프리징되어 작동하지 않음'
'' = '- 커널 등 각종 오류코드 화면으로 전환됨'
'' = '- 시스템이 즉시 종료됨'
'' = '- 일정 시간 클럭이 적용되나 시스템이 종료됨'
' ' = ''
'해결 방법' = ''
'' = '- 프리징이 걸린 경우, 전원 버튼 강제 종료'
'' = '- 권장 주파수보다 높게 설정한 경우 낮추기'
'' = '- 부스트 클럭을 낮추거나 부스트 모드 해제'
'' = '- 언더볼트 레벨, 고주파 언더볼트 조정'
'' = '- 테이블 설정을 자동으로 설정'
'' = '- 저주파/고주파 최소 전압 값 높이기'
'' = '- 전압 제한 값 높이기'