;override=OC Switchcraft EOS
;creator=Asa
;color=red

[@설정 가이드]
[gpu_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'GPU 오버클럭' = ' speedo: {gpu_speedo}IDDQ: {gpu_iddq}'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=5
;gap=28
'1. GPU 스케줄링 설정' = ''
'' = '시스템 설정  스케줄링  면  로 전환'
'' = 'Mariko의 경우  1305 MHz  면  로 전환'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=5
;gap=28
'2. 언더볼트 모드 설정' = ''
'' = '언더볼트 모드  High UV table 선택'

[manual]
;mode=table
;alignment=left
;offset=30
;spacing=5
;gap=28
'3. 전압 설정' = ''
erista:
'' = '최소 전압: 740-780 mV 내에서 설정'
' ' = ''
'' = '기호에 따라 커스텀 테이블 조정'
mariko:
'' = '최소 전압: 자동 선택'
'' = '최대 전압: 800-850 mV 내에서 설정'
' ' = ''
'' = '기호에 따라 커스텀 테이블 조정'

[manual]
;mode=table
;alignment=left
;offset=28
;spacing=5
;gap=28
erista:
'4. 전압 오프셋 설정' = ''
'' = '전압 오프셋: 0 에서 -30 내에서 설정'
mariko:
'4. 전압 오프셋 설정' = ''
'' = '전압 오프셋: 0 설정 혹은 -5,-10,-15 테스트'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=5
;gap=28
'5. 설정 저장 및 적용' = ''
'' = '백업 시스템  Slot  분류 선택  백업'
'' = ' Launcher+  에뮤/시스낸드 (커펌)  재부팅'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=5
'6. 동작 확인 (게임 실행)' = ''
'' = 'Ultrahand  오버레이  Sys-Clk-EOS'
'' = ' 프로필 편집  GPU  설정 클럭 선택'

[@추가 정보]
[gpu_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'오류 발생시' = ' speedo: {gpu_speedo}IDDQ: {gpu_iddq}'

[manual]
;mode=table
;alignment=left
;offset=20
;spacing=4
'안정 값이 아닌 경우, 발생하는 오류' = ''
'' = '- 화면이 깨지거나 프리징되어 작동하지 않음'
'' = '- 커널 등 각종 오류코드 화면으로 전환됨'
'' = '- 시스템이 즉시 종료됨'
'' = '- 일정 시간 클럭이 적용되나 시스템이 종료됨'
' ' = ''
'해결 방법' = ''
'' = '- 프리징이 걸린 경우, 전원 버튼 강제 종료'
'' = '- 권장 주파수보다 높게 설정한 경우 낮추기'
'' = '- 최대 전압 값 조정'
'' = '- 전압 오프셋 조정'
'' = '- 커스텀 테이블 기본 값으로 되돌리기'