;override=OC Switchcraft EOS
;creator=Asa
;color=red

[@설정 가이드]
[ram_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'RAM 오버클럭' = ' {ram_model}'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=0
json_file '/switch/.packages/OC Toolkit/json/ram_model.json'
'1. RAM 타이밍 설정' = ''
'' = '타이밍  제조사별 프리셋  {ram_vendor}'
'' = ' {json_file(0,{ram_model})}  Common 혹은 ST 선택'
'' = ' DRAM  AUTO_ADJ 혹은 HP 선택'
' ' = ''

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
;section_text_color=warning
' 프리셋이 없는 경우' = ''
'' = '직접 조정 또는 기본  Common 혹은 ST 선택'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
'2. RAM 최대 클럭 설정' = ''
'' = '시트 정보를 참고하여 허용 클럭 확인'
'' = ' 최대 클럭  주파수 선택'

[manual]
;mode=table
;alignment=left
;offset=35
;spacing=4
;gap=27
'3. 전압 및 테이블 설정' = ''
'' = 'Vddq 전압: 600-640 mV 내에서 설정'
'' = 'Vdd2 전압: 1100-1175 mV 내에서 설정'
'' = 'EMC DVB 테이블: 1-4 내에서 설정'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
;gap=27
'4. 설정 저장 및 적용' = ''
'' = '백업 시스템  Slot  분류 선택  백업'
'' = ' Launcher+  에뮤/시스낸드 (커펌)  재부팅'

[manual]
;mode=table
;alignment=center
;offset=8
;spacing=4
'5. 동작 확인 (게임 실행)' = ''
'' = 'Ultrahand  오버레이  Sys-Clk-EOS'
'' = ' 프로필 편집  RAM  설정 클럭 선택'

[@추가 정보]
[ram_guide]
;mode=table
;background=false
;header_indent=true
;section_text_color=header
;info_text_color=notice
'추가 정보' = ' {ram_model}'

[manual]
;mode=table
;alignment=left
;offset=20
;spacing=5
;gap=30
'Vddq · Vdd2 전압 다이어트 및 안정성 확인' = ''
'' = '1. 앞서 동작이 확인된 전압 값을 확인'
'' = '2. 해당 지점부터 전압 값을 낮추어 설정 저장'
'' = '3. 재부팅 후 게임 실행하여, 재설정한 클럭 적용'
'' = '4. 낮춘 전압 값이 동작하는지 확인'
'' = '5. 안정된 전력 값 내에서 실행되는지 확인'
'' = '6. 최소 1시간 이상 클럭이 유지되는지 확인'
'' = '7. 1-6 과정을 반복하여 최저 안정 값 확인'
'' = '8. 위 조건을 만족하면 설정 값을 백업'

[manual]
;mode=table
;alignment=left
;offset=20
;spacing=4
'안정 값이 아닌 경우, 발생하는 오류' = ''
'' = '- 화면이 깨지거나 프리징되어 작동하지 않음'
'' = '- 커널 등 각종 오류코드 화면으로 전환됨'
'' = '- 시스템이 즉시 종료됨'
'' = '- 일정 시간 클럭이 적용되나 시스템이 종료됨'
' ' = ''
'해결 방법' = ''
'' = '- 프리징이 걸린 경우, 전원 버튼 강제 종료'
'' = '- 권장 주파수보다 높게 설정한 경우 낮추기'
'' = '- 타이밍을 수동으로 조정'
'' = '- 프리셋 사용시 Common를 ST로 변경'
'' = '- AUTO_ADJ인 경우, AUTO_ADJ_HP로 변경'
'' = '- Vddq · Vdd2 전압 값 높이기'
'' = '- EMC DVB 테이블을 조정'