;override=OC Switchcraft EOS
;creator=ppkantorski, B3711, Asa
;color=red


[Loader.kip 프로파일]
[*Slot 0]
;mode=slot

[RAM Table 0]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 0.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot0]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 0.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot0]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[백업?slot0]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 0.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 0.ini' 
#set-ini-val './config.ini' '복원?slot0' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 0.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 0' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot0]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 0.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'


[제거?slot0]
;mode=default
del '/backup/kips/.OC/Slot 0.ini'
remove-ini-key './config.ini' '*분류?slot0' footer
remove-ini-key './config.ini' '백업?slot0' footer
remove-ini-key './config.ini' '복원?slot0' footer
remove-ini-section './config.ini' '*Slot 0'
refresh-to '제거' '' false



[*Slot 1]
;mode=slot

[RAM Table 1]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 1.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot1]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 1.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot1]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}


[백업?slot1]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 1.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 1.ini' 
#set-ini-val './config.ini' '복원?slot1' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 1.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 1' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot1]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 1.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'


[제거?slot1]
;mode=default
del '/backup/kips/.OC/Slot 1.ini'
remove-ini-key './config.ini' '*분류?slot1' footer
remove-ini-key './config.ini' '백업?slot1' footer
remove-ini-key './config.ini' '복원?slot1' footer
remove-ini-section './config.ini' '*Slot 1'
refresh-to '제거' '' false

[*Slot 2]
;mode=slot

[RAM Table 2]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 2.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot2]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 2.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot2]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}


[백업?slot2]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 2.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 2.ini' 
#set-ini-val './config.ini' '복원?slot2' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 2.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 2' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot2]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 2.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'

[제거?slot2]
;mode=default
del '/backup/kips/.OC/Slot 2.ini'
remove-ini-key './config.ini' '*분류?slot2' footer
remove-ini-key './config.ini' '백업?slot2' footer
remove-ini-key './config.ini' '복원?slot2' footer
remove-ini-section './config.ini' '*Slot 2'
refresh-to '제거' '' false


[*Slot 3]
;mode=slot

[RAM Table 3]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 3.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot3]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 3.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot3]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[백업?slot3]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 3.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 3.ini' 
#set-ini-val './config.ini' '복원?slot3' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 3.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 3' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot3]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 3.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'

[제거?slot3]
;mode=default
del '/backup/kips/.OC/Slot 3.ini'
remove-ini-key './config.ini' '*분류?slot3' footer
remove-ini-key './config.ini' '백업?slot3' footer
remove-ini-key './config.ini' '복원?slot3' footer
remove-ini-section './config.ini' '*Slot 3'
refresh-to '제거' '' false


[*Slot 4]
;mode=slot

[RAM Table 4]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 4.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot4]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 4.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot4]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[백업?slot4]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 4.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 4.ini' 
#set-ini-val './config.ini' '복원?slot4' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 4.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 4' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot4]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 4.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'

[제거?slot4]
;mode=default
del '/backup/kips/.OC/Slot 4.ini'
remove-ini-key './config.ini' '*분류?slot4' footer
remove-ini-key './config.ini' '백업?slot4' footer
remove-ini-key './config.ini' '복원?slot4' footer
remove-ini-section './config.ini' '*Slot 4'
refresh-to '제거' '' false

[*Slot 5]
;mode=slot

[RAM Table 5]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 5.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot5]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 5.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot5]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}


[백업?slot5]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 5.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 5.ini' 
#set-ini-val './config.ini' '복원?slot5' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 5.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 5' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot5]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 5.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'

[제거?slot5]
;mode=default
del '/backup/kips/.OC/Slot 5.ini'
remove-ini-key './config.ini' '*분류?slot5' footer
remove-ini-key './config.ini' '백업?slot5' footer
remove-ini-key './config.ini' '복원?slot5' footer
remove-ini-section './config.ini' '*Slot 5'
refresh-to '제거' '' false

[*Slot 6]
;mode=slot

[RAM Table 6]
;mode=table
;info_text_color=accent
;spacing=4
;gap=35
ini_file '/backup/kips/.OC/Slot 6.ini'
json_file './json/max_clocks.json'
'타이밍' = {ini_file(Backup,Timings)}
json_file './json/dram.json'
'DRAM'= {json_file(0,{ini_file(Backup,DRAM)})}
mariko:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzM)})}
json_file './json/vddq.json'
'Vddq' = {json_file(0,{ini_file(Backup,ramVDDQ)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}
erista:
json_file './json/max_clocks.json'
'최대 클럭' = {json_file(0,{ini_file(Backup,ramMHzE)})}
json_file './json/vdd2.json'
'Vdd2' = {json_file(0,{ini_file(Backup,ramVDD2)})}

[*상세?slot6]
;mode=forwarder
del '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 6.ini' '/backup/kips/.OC/tmp.ini'
package_source './backup_info.ini'

[*분류?slot6]
;mode=option
list_file_source ./backup_labels.txt
set-footer {list_file_source(*)}

[백업?slot6]
;mode=slot
del /backup/kips/.OC/tmp.ini
del '/backup/kips/.OC/Slot 6.ini'
exec backup
mv '/backup/kips/.OC/tmp.ini' '/backup/kips/.OC/Slot 6.ini' 
#set-ini-val './config.ini' '복원?slot6' footer '{timestamp("%Y-%m-%d %H:%M")}'
ini_file '/backup/kips/.OC/Slot 6.ini'
json_file './json/max_clocks.json'
set-ini-val './config.ini' '*Slot 6' footer {json_file(0,{ini_file(Backup,ramMHzM)})}
set-footer '{timestamp("%Y-%m-%d %H:%M")}'
refresh-to '백업' '' false

[복원?slot6]
;mode=slot
try:
delete '/backup/kips/.OC/tmp.ini'
cp '/backup/kips/.OC/Slot 6.ini' '/backup/kips/.OC/tmp.ini' 
exec restore
delete '/backup/kips/.OC/tmp.ini'
exec boot
set-footer '{timestamp("%Y-%m-%d %H:%M")}'

[제거?slot6]
;mode=default
del '/backup/kips/.OC/Slot 6.ini'
remove-ini-key './config.ini' '*분류?slot6' footer
remove-ini-key './config.ini' '백업?slot6' footer
remove-ini-key './config.ini' '복원?slot6' footer
remove-ini-section './config.ini' '*Slot 6'
refresh-to '제거' '' false

