;override=OC Switchcraft EOS
;creator=ppkantorski, B3711, Asa
;color=red

[@설정]

[RAM Table package]
;mode=table
;background=false
;spacing=4
;header_indent=true
;section_text_color=header
;info_text_color=notice
json_file './json/ram_model.json'
'RAM' = ' {ram_vendor} {json_file(0,{ram_model})}'


[*타이밍]
;mode=forwarder
;mini=true
exec cTimings
package_source './timings.ini'


[*DRAM]
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/ram_dram_timing.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 64 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back


[*최대 클럭?RAMmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/ram_freqs.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 80 {json_file_source(*,hex)}
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 52 {gpu_speedo}
set-footer '{json_file_source(*,label)}'
back


[*최대 클럭?RAMerista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './erista/ram_freqs.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 76 {json_file_source(*,dec)}
set-footer '{json_file_source(*,label)}'
back

[*Vddq]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/ram_vddq.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 72 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[*Vdd2]
;mode=option
;mini=true
;selection_mini=true
mariko:
json_file_source './mariko/ram_vdd2.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 68 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back
erista:
json_file_source './erista/ram_vdd2.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 68 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back


[EMC DVB 테이블?mariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_dvb_table.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 84 {json_file_source(*,hex)}


[EMC DVB 테이블?erista]
;system=erista
;mode=named_step_trackbar
;unlocked=true
json_file_source './erista/ram_dvb_table.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 84 {json_file_source(*,hex)}



[CPU]
[언더볼트 레벨?CPU]
;mode=named_step_trackbar
;unlocked=true
mariko:
json_file_source './mariko/cpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 12 {json_file_source(*,hex)}
erista:
json_file_source './erista/cpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 12 {json_file_source(*,hex)}


[고주파 언더볼트?CPU]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/cpu_high_uv.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 252 {json_file_source(*,hex)}

[*테이블 설정?CPUmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/cpu_table.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 272 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[*저주파 최소 전압?CPUmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/cpu_low_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 24 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[*최소 전압?CPUerista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './erista/cpu_low_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 16 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back


[*고주파 최소 전압?CPUmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/cpu_high_vmin.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 28 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back


[*전압 제한?CPUmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/cpu_voltages.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 32 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[*전압 제한?CPUerista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './erista/cpu_voltages.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 20 {json_file_source(*,dec)}
set-footer '{json_file_source(*,name)}'
back



[*부스트 클럭?CPU]
;mode=option
;mini=true
;selection_mini=true
mariko:
json_file_source './mariko/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 8 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back
erista:
json_file_source './erista/cpu_boost_clock.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 8 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back




[GPU]
[언더볼트 모드?GPUmariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/gpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 40 {json_file_source(*,hex)}


[언더볼트 모드?GPUerista]
;system=erista
;mode=named_step_trackbar
;unlocked=true
json_file_source './erista/gpu_uv.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 36 {json_file_source(*,hex)}

[자동 최소 전압]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './json/gpu_dvfs.json' name
set-ini-val /config/sys-clk/config.ini values auto_gpu_vmin {json_file_source(*,dvfs)}

[자동 최소 전압 오프셋?GPUmariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=true
json_file_source './json/gpu_dvfs_offset.json' name
set-ini-val /config/sys-clk/config.ini values gpu_vmin_offset {json_file_source(*,dvfs)}

[*최소 전압?GPUmariko]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/gpu_vmin.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 56 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[*최소 전압?GPUerista]
;system=erista
;mode=option
;mini=true
;selection_mini=true
json_file_source './erista/gpu_vmin.json' label
hex-by-custom-rdecimal-offset /atmosphere/kips/loader.kip CUST 48 {json_file_source(*,dec)}
set-footer '{json_file_source(*,name)}'
back

[*최대 전압?GPU]
;system=mariko
;mode=option
;mini=true
;selection_mini=true
json_file_source './mariko/gpu_vmax.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 60 {json_file_source(*,hex)}
set-footer '{json_file_source(*,name)}'
back

[전압 오프셋]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/gpu_volt_offset.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 44 {json_file_source(*,hex)}
set-ini-val /config/sys-clk/config.ini values auto_gpu_vmin 2

[*커스텀 테이블]
;mode=forwarder
;mini=true
exec cCutomTable
package_source './custom_table.ini'


[@도구]
[안내문]
;mode=table
;header_indent=true
;background=false
'안내:' = '설정 값 저장을 위해 재부팅이 필요합니다'

[*설정 값 확인]
;mode=forwarder
package_source './info.ini'

[*시스템 백업]
;mode=forwarder
exec cBackupSystem
package_source './backup.ini'

[*시스템 설정]
;mode=forwarder
exec cSystemSettings
package_source './system-settings.ini'

[*업데이트설명서]
;mode=forwarder
exec cUpdate
package_source './update.ini'

[*System Clock+]
;mode=forwarder
package_source '/switch/.packages/System Clock+/package.ini'

[크레딧]
[개발자]
;mode=table
;background=false
;spacing=0
;gap=0
;info_text_color=accent
'개발자:' = 'ppkantorski, B3711, edit by Asa'
'' = ''

[기여자]
;mode=table
;background=false
;spacing=5
'기여자:' = 'MestreYodaRossi, meha, lineon'
'' = 'efosamark, i3sey, irene, redraz'