;override=OC Switchcraft EOS
;creator=ppkantorski, B3711, Asa
;color=red

[@]
[System Settings]
;mode=table
;background=false
;header_indent=true
;info_text_color=warning
;section_text_color=header
'System' = ''

[컨트롤러 블루투스 동기화]
;mode=toggle
;mini=true
on:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x1
off:
set-ini-val /atmosphere/config/system_settings.ini atmosphere enable_external_bluetooth_db u8!0x0

[blank]
;mode=table
;background=false
;gap=20

[GPU]
;mode=table
;header_indent=true
;background=false
;section_text_color=header
;info_text_color=warning
mariko:
'GPU' = '1305 MHz는 스케줄링 활성화시에만 사용'
erista:
'GPU UV3' = '1075 MHz는 스케줄링 활성화시에만 사용'

[스케줄링]
;mode=toggle?on
;mini=true
on:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x1
set-ini-val './config.ini' '1305 MHz GPU' footer 'On'
refresh
off:
set-ini-val /atmosphere/config/system_settings.ini am.gpu gpu_scheduling_enabled u8!0x0
set-ini-val './config.ini' '1305 MHz GPU' footer 'Off'
refresh

[1305 MHz+]
;system=mariko
;mode=toggle
;mini=true
on:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 00
refresh
off:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 01
refresh

[1075 MHz+]
;system=erista
;mode=toggle
;mini=true
on:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 00
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 176 D007
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 180 D007
refresh
off:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 256 01
refresh

[blank]
;mode=table
;background=false
;gap=20

[CPU]
;mode=table
;header_indent=true
;background=false
;alignment=right
;spacing=3
;section_text_color=header
;info_text_color=warning
mariko:
'CPU' = '2601 MHz 는 고수율 기기를 제외하고'
'' = '치명적인 성능 저하를 초래할 수 있습니다'
erista:
'CPU' = '2295 MHz 는 불안정할 수 있습니다'

[CPU 최대 주파수?mariko]
;system=mariko
;mode=named_step_trackbar
;unlocked=false
json_file_source './mariko/cpu_max_freq.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 264 {json_file_source(*,hex)}

[2295 MHz]
;system=erista
;mode=toggle
on:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 264 01
off:
hex-by-custom-offset '/atmosphere/kips/loader.kip' CUST 264 00

[blank]
;mode=table
;background=false
;gap=20

[Fan curve]
;mode=table
;header_indent=true
;background=false
;alignment=right
;section_text_color=header
;info_text_color=accent
'팬 커브 ( 특성 곡선 )' = '권장 온도: 54°C'

[*Tskin 계수]
;mode=option
;mini=true
json_file_source './json/coefficients.json' name
set-ini-val '/atmosphere/config/system_settings.ini' tc tskin_pcb_coefficients_console_on_fwdbg str!"{json_file_source(*,pcb_cf_dk)}"
set-ini-val '/atmosphere/config/system_settings.ini' tc tskin_pcb_coefficients_handheld_on_fwdbg str!"{json_file_source(*,pcb_cf_hh)}"
set-ini-val '/atmosphere/config/system_settings.ini' tc tskin_soc_coefficients_console_on_fwdbg str!"{json_file_source(*,soc_cf_dk)}"
set-ini-val '/atmosphere/config/system_settings.ini' tc tskin_soc_coefficients_handheld_on_fwdbg str!"{json_file_source(*,soc_cf_hh)}"
set-footer '{json_file_source(*,name)}'

[Tskin Target]
;mode=step_trackbar
;unlocked=true
;min_value=52
;max_value=60
;units=°C
;unlocked=false
set-ini-val /atmosphere/config/system_settings.ini tc use_configurations_on_fwdbg u8!0x1
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_console_on_fwdbg 'str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, {value}000, 128, 255], [{value}000, 1000000, 255, 255]]"'
set-ini-val /atmosphere/config/system_settings.ini tc tskin_rate_table_handheld_on_fwdbg 'str!"[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 49000, 51, 128], [49000, {value}000, 128, 255], [{value}000, 1000000, 255, 255]]"'
set-ini-val /atmosphere/config/system_settings.ini tc holdable_tskin u32!0xEA60
set-ini-val /atmosphere/config/system_settings.ini tc touchable_tskin u32!0xEA60

[Tskin 제어 설정 제거]
;mini=true
remove-ini-section /atmosphere/config/system_settings.ini tc
remove-ini-section './config.ini' '*Tskin 계수'
remove-ini-section './config.ini' 'Tskin Target'
refresh