;override=OC Switchcraft EOS
;creator=ppkantorski, B3711, Asa
;color=red

[@Primary Timings]
[Vendor]
;mode=table
;background=false
;header_indent=true
;info_text_color=notice
hex_file '/atmosphere/kips/loader.kip'
json_file './json/numbers.json'
'현재 타이밍' = ' ({json_file(0,{hex_file(CUST,88,1)})}-{json_file(0,{hex_file(CUST,92,1)})}-{json_file(0,{hex_file(CUST,96,1)})}) {json_file(0,{hex_file(CUST,100,1)})}-{json_file(0,{hex_file(CUST,104,1)})}-{json_file(0,{hex_file(CUST,108,1)})}-{json_file(0,{hex_file(CUST,112,1)})}-{json_file(0,{hex_file(CUST,116,1)})}'

[*제조사별 프리셋]
;mode=forwarder
;mini=true
package_source './timing_presets.ini'

[Gap]
;mode=table
;background=false
;header=false
;gap=30

[Primary Timings]
;mode=table
;background=false
;header_indent=true
;info_text_color=notice
'Primary' = ' 1차 타이밍'


[T1 tRCD]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_trcd.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 88 {json_file_source(*,hex)}
exec cUpdateTimings


[T2 tRP]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_trp.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 92 {json_file_source(*,hex)}
exec cUpdateTimings

[T3 tRAS]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_tras.json' label
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 96 {json_file_source(*,hex)}
exec cUpdateTimings

[Gap]
;mode=table
;background=false
;header=false
;gap=10

[Secondary]
;mode=table
;background=false
;header_indent=true
;info_text_color=notice
'Secondary' = ' 2차 타이밍'

[T4 tRRD]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_trrd.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 100 {json_file_source(*,hex)}
exec cUpdateTimings

[T5 tRFC]
;mode=named_step_trackbar
;unlocked=true
mariko:
json_file_source './mariko/ram_trfc.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 104 {json_file_source(*,hex)}
exec cUpdateTimings
erista:
json_file_source './erista/ram_trfc.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 104 {json_file_source(*,hex)}
exec cUpdateTimings

[T6 tRTW]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_trtw.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 108 {json_file_source(*,hex)}
exec cUpdateTimings

[T7 tWTR]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_twtr.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 112 {json_file_source(*,hex)}
exec cUpdateTimings

[T8 tREFI]
;mode=named_step_trackbar
;unlocked=true
json_file_source './mariko/ram_trefi.json' name
hex-by-custom-offset /atmosphere/kips/loader.kip CUST 116 {json_file_source(*,hex)}
exec cUpdateTimings