;override=OC Switchcraft EOS
;creator=ppkantorski, B3711, Asa
;color=red


[@Primary Timings]
[RAM Table package]
;mode=table
;background=false
;spacing=4
;gap=20
;header_indent=true
;section_text_color=header
;info_text_color=notice
json_file './json/ram_model.json'
'내장 RAM' = ' {ram_vendor} {json_file(0,{ram_model})}'

[*기본]
;mode=forwarder
package_source './preset_default.ini'


[*SAMSUNG]
;mode=forwarder
package_source './preset_samsung.ini'


[*Micron]
;system=mariko
;mode=forwarder
package_source './preset_micron.ini'


[*SK Hynix]
;system=mariko
;mode=forwarder
package_source './preset_hynix.ini'