# Hex Color
BACK=0x1B1B1B
BLUE=0x00DDFF
LIME=0x9FEEC3
TEAL=0xC0D1E7
OLIVE=0x8CB3BE
WHITE=0xFFFFFF
GREEN=0x009A87
MAROON=0x6B8EFF
ORANGE=0xF89009
SILVER=0x9D9D9D
VIOLET=0xC1BEF9
YELLOW=0xEEC123
MAGENTA=0xEF5369

# Default settings
co=color
cd=copydir
cf=copyfile
dd=deldir
df=delfile
md=mkdir
pt=print
pl=println
pp=printpos
pe={pause() exit()}
wait={t=timer()while(timer()<(t+tw)){print()}}


# ASAP Install Supporter process: BACKUP & DELETE
clear();
pp(21,07)co(MAROON)pl("    ___   ______  __     ___    _____");
pp(21,08)co(MAROON)pl("   /   | /_  __/ / /    /   |  / ___/");
pp(21,09)co(MAROON)pl("  / /| |  / /   / /    / /| |  \__ \ ");
pp(21,10)co(MAROON)pl(" / ___ | / /   / /___ / ___ | ___/ / ");
pp(21,11)co(MAROON)pl("/_/  |_|/_/   /_____//_/  |_|/____/  ");
pp(45,13)co(YELLOW)pl("only for ASAP");
pp(18,15)co(TEAL)pl("===========================================");
pp(28,17)co(BLUE)pl("ASAP Install Supporter");
pp(22,19)co(LIME)pl("-----------------------------------");
pp(23,21)co(SILVER)pt("- ")co(TEAL)pt("Move  ")co(SILVER)pt(": ")co(VIOLET)pt("[Volum]")co(SILVER)pt("|")co(VIOLET)pt("[D-Pad]")co(SILVER)pt("|")co(VIOLET)pl("[Stick]");
pp(23,22)co(SILVER)pt("- ")co(TEAL)pt("Select")co(SILVER)pt(": ")co(VIOLET)pt("[Power]")co(SILVER)pt("|")co(VIOLET)pl("[A]");
pp(18,24)co(TEAL)pl("===========================================");
pp(19,26)co(WHITE)pt("[")co(ORANGE)pt(" STEP.1 ")co(WHITE)pt("]")co(LIME)pl(" Backup & Delete files/folders");
pp(13,28)co(TEAL)pl("-----------------------------------------------------");
pp(13,29)co(TEAL)pl();

# backup inmportant file and folder
pp(15,30)co(OLIVE);
cd("sd:/switch/DBIsaves/*", "sd:/backup/dumps/DBI/");
cd("sd:/switch/DBI/saves", "sd:/backup/dumps/DBI/");
cd("sd:/DBI", "sd:/backup/dumps/");

cf("sd:/config/ftpsrv/config.ini", "sd:/backup/ftpsrv.ini.bak");
cf("sd:/config/MissionControl/missioncontrol.ini", "sd:/backup/missioncontrol.ini.bak");
cf("sd:/config/sphaira/config.ini", "sd:/backup/sphaira.ini.bak");
cf("sd:/config/sys-clk/config.ini", "sd:/backup/kips/config.ini.bak");
cf("sd:/config/sys-con/config.ini", "sd:/backup/syscon.ini.bak");
cf("sd:/atmosphere/bluetooth_devices.db", "sd:/backup/bluetooth_devices.db.bak");
cf("sd:/switch/tinfoil/locations.conf", "sd:/backup/tinfoil/locations.conf.bak");
cf("sd:/switch/tinfoil/options.json", "sd:/backup/tinfoil/options.json.bak");
cf("sd:/switch/tinfoil/gdrive.token", "sd:/backup/tinfoil/gdrive.token.bak");

# delete old or crash file & folder
# Atmosphere
dd("sd:/atmosphere/automatic_backups");
dd("sd:/atmosphere/config_templates");
dd("sd:/atmosphere/contents/054e4f4558454000");
dd("sd:/atmosphere/contents/010000000000DA7A");
dd("sd:/atmosphere/contents/010000000000000D");
dd("sd:/atmosphere/contents/0100000000001013");
dd("sd:/atmosphere/contents/420000000000000B");
dd("sd:/atmosphere/contents/420000000000000E");
dd("sd:/atmosphere/crash_reports");
dd("sd:/atmosphere/erpt_reports");
dd("sd:/atmosphere/exefs_patches/bootlogo");
dd("sd:/atmosphere/exefs_patches/logo_sloth");
dd("sd:/atmosphere/exefs_patches/disable_remap_dialog");
dd("sd:/atmosphere/exefs_patches/es_patches");
dd("sd:/atmosphere/exefs_patches/nfim_ctest");
dd("sd:/atmosphere/exefs_patches/nim_ctest");
dd("sd:/atmosphere/fatal_errors");
dd("sd:/atmosphere/fatal_reports");
dd("sd:/atmosphere/flags");
dd("sd:/atmosphere/hb");
dd("sd:/atmosphere/kip_patches");
dd("sd:/atmosphere/kips");
dd("sd:/atmosphere/logs");
dd("sd:/atmosphere/update");

df("sd:/atmosphere/config/exosphere.bin");
df("sd:/atmosphere/config/system_settings_stock.ini");
df("sd:/atmosphere/contents/420000000007E51A/toolbox.json");
df("sd:/atmosphere/erpt_reports");
df("sd:/atmosphere/hosts/default.txt");
df("sd:/atmosphere/hosts/domains.txt");
df("sd:/atmosphere/hosts/sysdns.txt");
df("sd:/atmosphere/hosts/sysmmc.txt");
df("sd:/atmosphere/hbl.nsp");
df("sd:/atmosphere/package3.aio");
df("sd:/atmosphere/package3.ultra");
df("sd:/atmosphere/reboot_payload.bin");
df("sd:/atmosphere/stratosphere.romfs.aio");
df("sd:/atmosphere/stratosphere.romfs.ultra");
df("sd:/atmosphere/splash.png");

# bootloader
dd("sd:/bootloader/debug");

df("sd:/bootloader/ini/!kefir_updater.ini");
df("sd:/bootloader/ini/aio_update.ini");
df("sd:/bootloader/ini/atmostock.ini");
df("sd:/bootloader/ini/hekate_ipl.ini");
df("sd:/bootloader/ini/kefir_updater.ini");
df("sd:/bootloader/ini/no_oc.ini");

df("sd:/bootloader/payloads/biskeydump.bin");
df("sd:/bootloader/payloads/CommonProblemResolver.bin");
df("sd:/bootloader/payloads/DowngradeFixer.bin");
df("sd:/bootloader/payloads/FuseCheck.bin");
df("sd:/bootloader/payloads/hwfly_toolbox.bin");
df("sd:/bootloader/payloads/Instinct-NX_toolbox.bin");
df("sd:/bootloader/payloads/Lockpick_RCM.bin");
df("sd:/bootloader/payloads/Lockpick_RCM_Pro.bin");
df("sd:/bootloader/payloads/NetMan.bin");
df("sd:/bootloader/payloads/picofly_toolbox_0.2.bin");
df("sd:/bootloader/payloads/prodinfo_gen.bin.bin");
df("sd:/bootloader/payloads/TegraExplorer.bin");
df("sd:/bootloader/payloads/program_fuse_odm4_t210_t210b01.bin");
df("sd:/bootloader/payloads/Warmboot_Extractor.bin");
df("sd:/bootloader/res/atmosphere.bmp");
df("sd:/bootloader/res/emummc.bmp");
df("sd:/bootloader/res/icon_atmosphere.bmp");
df("sd:/bootloader/res/icon_payload.bmp");
df("sd:/bootloader/res/icon_semistock.bmp");
df("sd:/bootloader/res/icon_stock.bmp");
df("sd:/bootloader/res/icon_switch.bmp");
df("sd:/bootloader/res/ku.bmp");
df("sd:/bootloader/res/ofw.bmp");
df("sd:/bootloader/res/stock.bmp");
df("sd:/bootloader/res/switch.bmp");
df("sd:/bootloader/res/sysnand.bmp");
df("sd:/bootloader/res/event_bg.bmp");
df("sd:/bootloader/res/event_pf.bmp");
df("sd:/bootloader/sys/module_sample.bso");
df("sd:/bootloader/bootlogo.bmp");
df("sd:/bootloader/bootlogo_kefir.bmp");
df("sd:/bootloader/hekate_ipl.ini");
df("sd:/bootloader/hekate_ipl.ini.template");
df("sd:/bootloader/hekate_ipl_.ini");
df("sd:/bootloader/nyx.ini");
df("sd:/bootloader/nyx.ini_");
df("sd:/bootloader/patches.ini");
df("sd:/bootloader/update.bin.sig");
df("sd:/bootloader/updating.bmp");

# config
dd("sd:/config/aio-switch-updater");
dd("sd:/config/fusecheck");
dd("sd:/config/hats-tools");
dd("sd:/config/ASAP-Updater");
dd("sd:/config/kefir-updater");
dd("sd:/config/nx-hbmenu");
dd("sd:/config/oc");
dd("sd:/config/status-monitor");
dd("sd:/config/sys-patch");
dd("sd:/config/tesla");
dd("sd:/config/uberhand");
dd("sd:/config/ultrahand/downloads");
dd("sd:/config/ultrahand/flag");
dd("sd:/config/ultrahand/lang");
dd("sd:/config/ultrahand/themes");
dd("sd:/config/ultrahand/wallpapers");

df("sd:/config/sys-clk/config.ini.template");
df("sd:/config/sys-con/config_dualshock3.ini");
df("sd:/config/sys-con/config_dualshock4.ini");
df("sd:/config/sys-con/config_global.ini");
df("sd:/config/sys-con/config_xbox360.ini");
df("sd:/config/sys-con/config_xboxone.ini");
df("sd:/config/sys-con/config_xboxorig.ini");
df("sd:/config/sys-con/example.ini");
df("sd:/config/ultrahand/config.ini");
df("sd:/config/ultrahand/fuse.ini");
df("sd:/config/ultrahand/theme.ini");
df("sd:/config/ultrahand/RELEASE.ini");
df("sd:/config/ultrahand/ram_8gb.ini");
df("sd:/config/ultrahand/wallpaper.rgba");
df("sd:/config/quickntp.ini");

# switch
dd("sd:/switch/.overlays/.offload");
dd("sd:/switch/.packages/DBI");
dd("sd:/switch/.packages/SC Wizard");
dd("sd:/switch/.packages/Setting");
dd("sd:/switch/.packages/System Tweaks");
dd("sd:/switch/.packages/Theme");
dd("sd:/switch/.packages/Translate Interface");
dd("sd:/switch/aio-switch-updater");
dd("sd:/switch/appstore");
dd("sd:/switch/breeze");
dd("sd:/switch/ChoiDujourNX");
dd("sd:/switch/DBI/saves");
dd("sd:/switch/DBI/logs");
dd("sd:/switch/DBI/dumps");
dd("sd:/switch/DBI_RU");
dd("sd:/switch/DeepSea-Toolbox");
dd("sd:/switch/Edizon");
dd("sd:/switch/Fizeau");
dd("sd:/switch/ftpsrv");
dd("sd:/switch/games");
dd("sd:/switch/Goldleaf");
dd("sd:/switch/Haku33");
dd("sd:/switch/hats-tools");
dd("sd:/switch/Haze");
dd("sd:/switch/incognito");
dd("sd:/switch/JKSV");
dd("sd:/switch/kefir-updater");
dd("sd:/switch/KosmosToolbox");
dd("sd:/switch/KosmosUpdater");
dd("sd:/switch/LinkUser");
dd("sd:/switch/Lockpick");
dd("sd:/switch/MemTesterNX");
dd("sd:/switch/mercury");
dd("sd:/switch/mhz");
dd("sd:/switch/Quick-Reboot");
dd("sd:/switch/Reboot to payload");
dd("sd:/switch/Reboot_to_payload");
dd("sd:/switch/sigpatch-updater");
dd("sd:/switch/Switch_90DNS_tester");
dd("sd:/switch/sys-clk-manager");
dd("sd:/switch/sx");
dd("sd:/switch/tinfoil/nsp");
dd("sd:/switch/tinfoil/themes/ASAP_Ghost");
dd("sd:/switch/tinfoil/themes/ASAP_GDF");
dd("sd:/switch/tinwoo");
dd("sd:/switch/TinyMemBenchNX");

df("sd:/switch/.overlays/DNS-MITM_Manager.ovl");
df("sd:/switch/.overlays/Observer-Tool.ovl");
df("sd:/switch/.overlays/QuickNTP.ovl");
df("sd:/switch/.overlays/Quick-Reboot.ovl");
df("sd:/switch/.packages/OC Toolkit/erista/gpu_uv3_e.json");
df("sd:/switch/.packages/OC Toolkit/erista/gpu_uv3.json");
df("sd:/switch/.packages/OC Toolkit/erista/ram_vdd2.json");
df("sd:/switch/.packages/OC Toolkit/mariko/cpu_voltages.json");
df("sd:/switch/.packages/OC Toolkit/mariko/gpu_uv3_e.json");
df("sd:/switch/.packages/OC Toolkit/mariko/gpu_uv3.json");
df("sd:/switch/.packages/OC Toolkit/mariko/gpu_vmax.json");
df("sd:/switch/.packages/OC Toolkit/mariko/ram_vdd2.json");
df("sd:/switch/.packages/OC Toolkit/mariko/ram_vddq.json");
df("sd:/switch/.packages/OC Toolkit/backup_info.ini");
df("sd:/switch/.packages/OC Toolkit/custom_table.ini");
df("sd:/switch/.packages/OC Toolkit/info.ini");
df("sd:/switch/.packages/OC Toolkit/update.ini");
df("sd:/switch/.packages/.offload/ram_expansion/nyx_4gb.bin");
df("sd:/switch/.packages/.offload/ram_expansion/nyx_8gb.bin");
df("sd:/switch/.packages/package.ini");
df("sd:/switch/AmiiboGenerator.nro");
df("sd:/switch/appstore.nro");
df("sd:/switch/battery_desync_fix.nro");
df("sd:/switch/Browser.nro");
df("sd:/switch/chiaki.nro");
df("sd:/switch/daybreak.nro");
df("sd:/switch/edizon.nro");
df("sd:/switch/Fizeau.nro");
df("sd:/switch/ftpsrv.nro");
df("sd:/switch/Goldleaf.nro");
df("sd:/switch/haze.nro");
df("sd:/switch/hbmenu.nro");
df("sd:/switch/Hekate-Toolbox.nro");
df("sd:/switch/Hekate_Toolbox.nro");
df("sd:/switch/JKSV.nro");
df("sd:/switch/joy-con_utility.nro");
df("sd:/switch/ldnmitm_config.nro");
df("sd:/switch/linkalho.nro");
df("sd:/switch/melonDS.nro");
df("sd:/switch/mgba.nro");
df("sd:/switch/Moonlight-Switch.nro");
df("sd:/switch/NX-Activity-Log.nro");
df("sd:/switch/nxdumptool.nro");
df("sd:/switch/nxmp.nro");
df("sd:/switch/NX-Shell.nro");
df("sd:/switch/NxThemesinstaller.nro");
df("sd:/switch/Quick-Reboot.nro");
df("sd:/switch/reboot_to_payload.nro");
df("sd:/switch/reboot_to_hekate.nro");
df("sd:/switch/ReverseNX-Tool.nro");
df("sd:/switch/sphaira.nro");
df("sd:/switch/Sigpatch-Updater.nro");
df("sd:/switch/SimpleModDownloader.nro");
df("sd:/switch/SimpleModManager.nro");
df("sd:/switch/Switch_90DNS_tester.nro");
df("sd:/switch/sys-clk-manager.nro");
df("sd:/switch/SysDVR-conf.nro");
df("sd:/switch/tinfoil/keys.txt");
df("sd:/switch/vgedit.nro");

# etc.
dd("sd:/ams");
dd("sd:/atmo");
dd("sd:/firmware");
dd("sd:/games");
dd("sd:/music");
dd("sd:/modules");
dd("sd:/nsp");
dd("sd:/NSPs");
dd("sd:/oc");
dd("sd:/pegascape");
dd("sd:/tegraexplorer");
dd("sd:/TinGen");
dd("sd:/themes");
dd("sd:/tools");
dd("sd:/SaltySD/plugins/ReverseNX");
dd("sd:/SaltySD/plugins/NX-FPS");
dd("sd:/sept");
dd("sd:/scripts");
dd("sd:/sxos");
dd("sd:/SAFE");
dd("sd:/SYSTEM");
dd("sd:/USER");
dd("sd:/.DS_Store");
dd("sd:/.git");
dd("sd:/.Trash-1000");

df("sd:/emuiibo/overlay/lang/de.json");
df("sd:/emuiibo/overlay/lang/es.json");
df("sd:/emuiibo/overlay/lang/fr.json");
df("sd:/emuiibo/overlay/lang/it.json");
df("sd:/emuiibo/overlay/lang/pt-BR.json");
df("sd:/emuiibo/overlay/lang/ru.json");
df("sd:/emuiibo/overlay/lang/zh-Hans.json");
df("sd:/emuiibo/overlay/lang/zh-Hant.json");
df("sd:/SaltySD/plugins/NX-FPS.elf");
df("sd:/SaltySD/plugins/ReverseNX.elf");

df("sd:/BCPKG2-1-Normal-Main");
df("sd:/BCPKG2-1-Normal-Main.bin");
df("sd:/BCPKG2-2-Normal-Sub");
df("sd:/BCPKG2-2-Normal-Sub.bin");
df("sd:/BCPKG2-3-SafeMode-Main");
df("sd:/BCPKG2-3-SafeMode-Main.bin");
df("sd:/BCPKG2-4-SafeMode-Sub");
df("sd:/BCPKG2-4-SafeMode-Sub.bin");
df("sd:/BCPKG2-5-Repair-Main");
df("sd:/BCPKG2-5-Repair-Main.bin");
df("sd:/BCPKG2-6-Repair-Sub");
df("sd:/BCPKG2-6-Repair-Sub.bin");
df("sd:/boot.bis");
df("sd:/BOOT0.bin");
df("sd:/BOOT1.bin");
df("sd:/.dropbox.device")
df("sd:/exosphere.ini");
df("sd:/firmware.bin");
df("sd:/.git");
df("sd:/hbmenu.nro");
df("sd:/install.bat");
df("sd:/manifest.json");
df("sd:/payload.bin");
df("sd:/payload.bin.aio");
df("sd:/payload_8gb.bin");
df("sd:/README.md");
df("sd:/sphaira.nro");
df("sd:/tinfoil.install.log");
df("sd:/update.bin");
df("sd:/.DS_Store");
df("sd:/.Trash-1000");

# if update ASAP
md("sd:/atmosphere/flags");
md("sd:/atmosphere/kips");

cf("sd:/switch/ASAP-Updater/ASAP-Updater_.nro", "sd:/switch/ASAP-Updater/ASAP-Updater.nro");
cf("sd:/bootloader/payloads/fusee.bin", "sd:/atmosphere/reboot_payload.bin");
cf("sd:/backup/bluetooth_devices.db.bak", "sd:/atmosphere/bluetooth_devices.db");
cf("sd:/backup/keys/prod.keys", "sd:/switch/prod.keys");
cf("sd:/config/ftpsrv/config_.ini", "sd:/config/ftpsrv/config.ini");
cf("sd:/backup/ftpsrv.ini.bak", "sd:/config/ftpsrv/config.ini");
cf("sd:/config/MissionControl/missioncontrol_.ini", "sd:/config/MissionControl/missioncontrol.ini");
cf("sd:/backup/missioncontrol.ini.bak", "sd:/config/MissionControl/missioncontrol.ini");
cf("sd:/config/sphaira/config_.ini", "sd:/config/sphaira/config.ini");
cf("sd:/backup/sphaira.ini.bak", "sd:/config/sphaira/config.ini");
cf("sd:/config/sys-con/config_.ini", "sd:/config/sys-con/config.ini");
cf("sd:/backup/syscon.ini.bak", "sd:/config/sys-con/config.ini");
cf("sd:/config/sys-clk/config_.ini", "sd:/config/sys-clk/config.ini");
cf("sd:/backup/kips/config.ini.bak", "sd:/config/sys-clk/config.ini");
cf("sd:/backup/tinfoil/locations.conf.bak", "sd:/switch/tinfoil/locations.conf");
cf("sd:/backup/tinfoil/gdrive.token.bak", "sd:/switch/tinfoil/gdrive.token");
cf("sd:/backup/tinfoil/options.json.bak", "sd:/switch/tinfoil/options.json");
cf("sd:/bootloader/update.bin", "sd:/switch/.packages/.offload/ram_expansion/hekate_4gb.bin");
cf("sd:/bootloader/update.bin", "sd:/payload.bin");

df("sd:/config/ftpsrv/config_.ini");
df("sd:/config/MissionControl/missioncontrol_.ini");
df("sd:/config/sphaira/config_.ini");
df("sd:/config/sys-clk/config_.ini");
df("sd:/config/sys-con/config_.ini");
df("sd:/backup/ftpsrv.ini.bak");
df("sd:/backup/missioncontrol.ini.bak");
df("sd:/backup/sphaira.ini.bak");
df("sd:/backup/syscon.ini.bak");
df("sd:/backup/bluetooth_devices.db.bak");
df("sd:/switch/ASAP-Updater/ASAP-Updater_.nro");

pp(01,30)co(SILVER)pt("                                   -")co(GREEN)pt(" Done ")co(SILVER)pl("-                                   ");
wait(tw = 1000);


# ASAP Install Supporter process: DEVICE
pp(19,26)co(WHITE)pt("   [")co(ORANGE)pt(" STEP.2 ")co(WHITE)pt("]")co(MAGENTA)pl(" Select your device type   ");
pp(27,30)opDV=["* Erista [Old/Patched]", "* Mariko [IBL/Lite/OLED]"];
resDV=menu(opDV, 1);
co(BACK)

if (resDV == 0){
	cf("sd:/bootloader/payloads/fusee.bin", "sd:/switch/.packages/.offload/ram_expansion/fusee_4gb.bin");
	dd("sd:/warmboot_mariko");
	df("sd:/bootloader/update.te");
}

if (resDV == 1){
	cf("sd:/bootloader/payloads/fusee.bin", "sd:/switch/.packages/.offload/ram_expansion/fusee_4gb.bin");
	dd("sd:/switch/Reboot2payload");
	df("sd:/bootloader/update.te");
	df("sd:/boot.dat");
	df("sd:/boot.ini");
}

pp(24,30)co(SILVER)pt("-")co(GREEN)pt(" Install or Update Completed ")co(SILVER)pl("-");
pp(27,31)co(BACK)pl("                        ");
pp(22,32)co(ORANGE)pl("Auto Reboot to ASAP after 3 seconds");
wait(tw = 3000);
payload("sd:/payload.bin");