# Hex Color
BACK=0x1B1B1B
BLUE=0x00DDFF
LIME=0x9FEEC3
TEAL=0xC0D1E7
OLIVE=0x8CB3BE
WHITE=0xFFFFFF
GREEN=0x009A87
MAROON=0x6B8EFF
ORANGE=0xF89009
SILVER=0x9D9D9D
VIOLET=0xC1BEF9
YELLOW=0xEEC123
MAGENTA=0xEF5369

# Default settings
co=color
cd=copydir
cf=copyfile
dd=deldir
df=delfile
md=mkdir
pt=print
pl=println
pp=printpos
pe={pause() exit()}
wait={t=timer()while(timer()<(t+tw)){print()}}


# ASAP Install Supporter process: BACKUP & DELETE
clear();
pp(21,07)co(MAROON)pl("    ___   ______  __     ___    _____");
pp(21,08)co(MAROON)pl("   /   | /_  __/ / /    /   |  / ___/");
pp(21,09)co(MAROON)pl("  / /| |  / /   / /    / /| |  \__ \ ");
pp(21,10)co(MAROON)pl(" / ___ | / /   / /___ / ___ | ___/ / ");
pp(21,11)co(MAROON)pl("/_/  |_|/_/   /_____//_/  |_|/____/  ");
pp(45,13)co(YELLOW)pl("only for ASAP");
pp(18,15)co(TEAL)pl("===========================================");
pp(28,17)co(BLUE)pl("ASAP Install Supporter");
pp(22,19)co(LIME)pl("-----------------------------------");
pp(23,21)co(SILVER)pt("- ")co(TEAL)pt("Move  ")co(SILVER)pt(": ")co(VIOLET)pt("[Volum]")co(SILVER)pt("|")co(VIOLET)pt("[D-Pad]")co(SILVER)pt("|")co(VIOLET)pl("[Stick]");
pp(23,22)co(SILVER)pt("- ")co(TEAL)pt("Select")co(SILVER)pt(": ")co(VIOLET)pt("[Power]")co(SILVER)pt("|")co(VIOLET)pl("[A]");
pp(18,24)co(TEAL)pl("===========================================");
pp(19,26)co(WHITE)pt("[")co(ORANGE)pt(" STEP.1 ")co(WHITE)pt("]")co(LIME)pl(" Backup & Delete files/folders");
pp(13,28)co(TEAL)pl("-----------------------------------------------------");
pp(13,29)co(TEAL)pl();

# backup inmportant file and folder
pp(15,30)co(OLIVE);
# DBI dumps
cd("sd:/backup/saves", "sd:/backup/dumps");
cd("sd:/switch/DBI/saves", "sd:/backup/dumps");
cd("sd:/switch/DBI/dumps", "sd:/backup/");

# config backups
cd("sd:/config/MissionControl/controllers", "sd:/backup/configs/");

cf("sd:/atmosphere/bluetooth_devices.db", "sd:/backup/configs/bluetooth_devices.bak");
cf("sd:/bootloader/nyx.ini", "sd:/backup/configs/nyx.bak");
cf("sd:/config/ftpsrv/config.ini", "sd:/backup/configs/ftpsrv.bak");
cf("sd:/config/MissionControl/missioncontrol.ini", "sd:/backup/configs/missioncontrol.bak");
cf("sd:/config/sphaira/config.ini", "sd:/backup/configs/sphaira.bak");
cf("sd:/config/sys-clk/config.ini", "sd:/backup/configs/sys-clk.bak");
cf("sd:/config/horizon-oc/config.ini", "sd:/backup/configs/hoc-clk.bak");
cf("sd:/config/sys-con/config.ini", "sd:/backup/configs/sys-con.bak");
cf("sd:/config/sys-con/config_dualshock3.ini", "sd:/backup/configs/sc_dualshock3.bak");
cf("sd:/config/sys-con/config_dualshock4.ini", "sd:/backup/configs/sc_dualshock4.bak");
cf("sd:/config/sys-con/config_global.ini", "sd:/backup/configs/sc_global.bak");
cf("sd:/config/sys-con/config_xbox360.ini", "sd:/backup/configs/sc_xbox360.bak");
cf("sd:/config/sys-con/config_xboxone.ini", "sd:/backup/configs/sc_xboxone.bak");
cf("sd:/config/sys-con/config_xboxorig.ini", "sd:/backup/configs/sc_xboxorig.bak");
cf("sd:/switch/DBI/dbi.config", "sd:/backup/configs/dbi.bak");
cf("sd:/switch/tinfoil/locations.conf", "sd:/backup/configs/tf_locations.bak");
cf("sd:/switch/tinfoil/gdrive.token", "sd:/backup/configs/tf_token.bak");
cf("sd:/switch/tinfoil/options.json", "sd:/backup/configs/tf_options.bak");

# delete old or crash file & folder
# atmosphere
dd("sd:/atmosphere/automatic_backups");
dd("sd:/atmosphere/config_templates");
dd("sd:/atmosphere/contents/00FF004D454D54FF"); # MemToolkitNX
dd("sd:/atmosphere/contents/054e4f4558454000"); # noexs
dd("sd:/atmosphere/contents/010000000000000D"); # dmnt
dd("sd:/atmosphere/contents/0100000000001013"); # myPage
dd("sd:/atmosphere/contents/420000000000000B"); # sys-patch
dd("sd:/atmosphere/contents/420000000000000E"); # ftpd
dd("sd:/atmosphere/crash_reports");
dd("sd:/atmosphere/erpt_reports");
dd("sd:/atmosphere/exefs_patches/am_dev_function");
dd("sd:/atmosphere/exefs_patches/capsrv_debug");
dd("sd:/atmosphere/exefs_patches/disable_ca_verification");
dd("sd:/atmosphere/exefs_patches/disable_remap_dialog");
dd("sd:/atmosphere/exefs_patches/es_patches");
dd("sd:/atmosphere/exefs_patches/fatal_force_extra_info");
dd("sd:/atmosphere/exefs_patches/logo_sloth");
dd("sd:/atmosphere/exefs_patches/nfim_ctest");
dd("sd:/atmosphere/exefs_patches/nim_ctest");
dd("sd:/atmosphere/exefs_patches/vi_debug");
dd("sd:/atmosphere/fatal_errors");
dd("sd:/atmosphere/fatal_reports");
dd("sd:/atmosphere/flags");
dd("sd:/atmosphere/kip_patches");
dd("sd:/atmosphere/kips");
dd("sd:/atmosphere/logs");
dd("sd:/atmosphere/nro_patches");
dd("sd:/atmosphere/update");

df("sd:/atmosphere/contents/.DS_Store");
df("sd:/atmosphere/config/sys-patch_config.ini");
df("sd:/atmosphere/config/system_settings_stock.ini");
df("sd:/atmosphere/contents/00FF0000636C6BFF/toolbox.json");
df("sd:/atmosphere/contents/420000000007E51A/toolbox.json");
df("sd:/atmosphere/erpt_reports");
df("sd:/atmosphere/hosts/default.txt");
df("sd:/atmosphere/hosts/domains.txt");
df("sd:/atmosphere/hosts/sysdns.txt");
df("sd:/atmosphere/hosts/sysmmc.txt");
df("sd:/atmosphere/.DS_Store");
df("sd:/atmosphere/exosphere.bin");
df("sd:/atmosphere/hbl.nsp");
df("sd:/atmosphere/mesosphere.bin");
df("sd:/atmosphere/package3.ultra");
df("sd:/atmosphere/reboot_payload.bin");
df("sd:/atmosphere/splash.png");
df("sd:/atmosphere/stratosphere.romfs.ultra");

# backup
dd("sd:/backup/kips");
dd("sd:/backup/tinfoil");

df("sd:/backup/configs/tf_locations.bak");
df("sd:/backup/configs/tf_token.bak");
df("sd:/backup/configs/tf_options.bak");

# bootloader
dd("sd:/bootloader/debug");

# ini boot configs
df("sd:/bootloader/ini/!kefir_updater.ini");
df("sd:/bootloader/ini/aio_update.ini");
df("sd:/bootloader/ini/atmostock.ini");
df("sd:/bootloader/ini/cfw_emummc_no_kip.ini");
df("sd:/bootloader/ini/cfw_sysnand_no_kip.ini");
df("sd:/bootloader/ini/kefir_updater.ini");
df("sd:/bootloader/ini/more_configs.ini");
df("sd:/bootloader/ini/no_oc.ini");

# payloads
df("sd:/bootloader/payloads/CommonProblemResolver.bin");
df("sd:/bootloader/payloads/DowngradeFixer.bin");
df("sd:/bootloader/payloads/FuseCheck.bin");
df("sd:/bootloader/payloads/hwfly_toolbox.bin");
df("sd:/bootloader/payloads/Instinct-NX_toolbox.bin");
df("sd:/bootloader/payloads/KitNX.bin");
df("sd:/bootloader/payloads/Lockpick_RCM.bin");
df("sd:/bootloader/payloads/Lockpick_RCM_Pro.bin");
df("sd:/bootloader/payloads/NetMan.bin");
df("sd:/bootloader/payloads/picofly_toolbox_0.2.bin");
df("sd:/bootloader/payloads/ProdinForge.bin");
df("sd:/bootloader/payloads/prodinfo_gen.bin.bin");
df("sd:/bootloader/payloads/program_fuse_odm4_t210_t210b01.bin");
df("sd:/bootloader/payloads/TegraExplorer.bin");
df("sd:/bootloader/payloads/TegraExplorer-Ext.bin");
df("sd:/bootloader/payloads/update.bin");
df("sd:/bootloader/payloads/Warmboot_Extractor.bin");

# event wallpapers
#df("sd:/bootloader/res/event_bg.bmp");
#df("sd:/bootloader/res/event_pf.bmp");
#df("sd:/bootloader/res/background.bmp");
#df("sd:/bootloader/res/profile.bmp");

# resource images
df("sd:/bootloader/res/atmo_cfw.bmp");
df("sd:/bootloader/res/atmo_sm.bmp");
df("sd:/bootloader/res/atmosphere.bmp");
df("sd:/bootloader/res/bootscreen.bmp");
df("sd:/bootloader/res/emummc.bmp");
df("sd:/bootloader/res/emunand_boot.bmp");
df("sd:/bootloader/res/extra_ram_boot.bmp");
df("sd:/bootloader/res/icon_atmosphere.bmp");
df("sd:/bootloader/res/icon_payload.bmp");
df("sd:/bootloader/res/icon_semistock.bmp");
df("sd:/bootloader/res/icon_stock.bmp");
df("sd:/bootloader/res/icon_switch.bmp");
df("sd:/bootloader/res/ku.bmp");
df("sd:/bootloader/res/ofw.bmp");
df("sd:/bootloader/res/stock.bmp");
df("sd:/bootloader/res/stock_boot.bmp");
df("sd:/bootloader/res/stock_nobox.bmp");
df("sd:/bootloader/res/switch.bmp");
df("sd:/bootloader/res/sys_boot.bmp");
df("sd:/bootloader/res/sys_cfw_nobox.bmp");
df("sd:/bootloader/res/sys_sm_nobox.bmp");
df("sd:/bootloader/res/sysmmc.bmp");

# not used
df("sd:/bootloader/sys/module_sample.bso");
df("sd:/bootloader/bootlogo.bmp");
df("sd:/bootloader/bootlogo_kefir.bmp");
df("sd:/bootloader/hekate_ipl.ini");
df("sd:/bootloader/hekate_ipl_.ini");
df("sd:/bootloader/nyx.ini");
df("sd:/bootloader/nyx.ini_");
df("sd:/bootloader/patches.ini");
df("sd:/bootloader/updating.bmp");

# config
dd("sd:/config/8gb");
dd("sd:/config/aio-switch-updater");
dd("sd:/config/fusecheck");
dd("sd:/config/hats-tools");
dd("sd:/config/horizon-oc");
dd("sd:/config/ASAP-Updater");
dd("sd:/config/kefir-updater");
dd("sd:/config/kitnx");
dd("sd:/config/lockpick_rcm_pro");
dd("sd:/config/nx-hbmenu");
dd("sd:/config/oc");
dd("sd:/config/prodinforge");
dd("sd:/config/status-monitor/lang");
dd("sd:/config/sys-patch");
dd("sd:/config/tesla");
dd("sd:/config/uberhand");
dd("sd:/config/ultrahand/.sounds");
dd("sd:/config/ultrahand/downloads");
dd("sd:/config/ultrahand/expansion");
dd("sd:/config/ultrahand/flags");
dd("sd:/config/ultrahand/lang");
dd("sd:/config/ultrahand/notifications");
dd("sd:/config/ultrahand/payloads");
dd("sd:/config/ultrahand/themes");
dd("sd:/config/ultrahand/wallpapers");

df("sd:/config/MissionControl/missioncontrol.ini.template");
df("sd:/config/status-monitor/config.ini.template");
df("sd:/config/sys-clk/config.ini.template");
df("sd:/config/sys-con/config.ini");
df("sd:/config/sys-con/config_dualshock3.ini");
df("sd:/config/sys-con/config_dualshock4.ini");
df("sd:/config/sys-con/config_global.ini");
df("sd:/config/sys-con/config_xbox360.ini");
df("sd:/config/sys-con/config_xboxone.ini");
df("sd:/config/sys-con/config_xboxorig.ini");
df("sd:/config/sys-con/example.ini");
df("sd:/config/ultrahand/.DS_Store");
df("sd:/config/ultrahand/config.ini");
df("sd:/config/ultrahand/fuse.ini");
df("sd:/config/ultrahand/RELEASE.ini");
df("sd:/config/ultrahand/theme.ini");
df("sd:/config/ultrahand/ram_8gb.ini");
df("sd:/config/ultrahand/wallpaper.rgba");
df("sd:/config/.DS_Store");
df("sd:/config/.skip");
df("sd:/config/quickntp.ini");

# switch
dd("sd:/switch/.packages/Alchemist");
dd("sd:/switch/.packages/Easy Setup");
dd("sd:/switch/.packages/Ez");
dd("sd:/switch/.packages/Lightning");
dd("sd:/switch/.packages/Memory Kit");
dd("sd:/switch/.packages/RAM Patch");
dd("sd:/switch/.packages/Settings");
dd("sd:/switch/.packages/Software");
dd("sd:/switch/.packages/Theme");
dd("sd:/switch/.packages/Translate Interface");
dd("sd:/switch/.packages/Ultra Tuner");
dd("sd:/switch/aio-switch-updater");
dd("sd:/switch/DBI/saves");
dd("sd:/switch/DBI/logs");
dd("sd:/switch/DBI/dumps");
dd("sd:/switch/DBI_RU");
dd("sd:/switch/Goldleaf");
dd("sd:/switch/hats-tools");
dd("sd:/switch/kefir-updater");
dd("sd:/switch/Switch_90DNS_tester");
dd("sd:/switch/sys-clk-manager");
dd("sd:/switch/tinfoil");
dd("sd:/switch/tinwoo");

df("sd:/switch/.overlays/Horizon-OC-Monitor.ovl");
df("sd:/switch/.overlays/QuickNTP.ovl");
df("sd:/switch/.overlays/sys-clk-overlay.ovl");
df("sd:/switch/.overlays/sys-patch-overlay.ovl");
df("sd:/switch/.packages/.offload/ram_expansion/fusee.bin");
df("sd:/switch/.packages/.offload/ram_expansion/fusee_40mb.bin");
df("sd:/switch/.packages/.offload/ram_expansion/fusee_4gb.bin");
df("sd:/switch/.packages/.offload/ram_expansion/fusee_8gb.bin");
df("sd:/switch/.packages/.offload/ram_expansion/package3");
df("sd:/switch/.packages/.offload/ram_expansion/package3_40mb");
df("sd:/switch/.packages/.offload/ram_expansion/stratosphere.romfs");
df("sd:/switch/.packages/.offload/ram_expansion/stratosphere_40mb.romfs");
df("sd:/switch/.packages/.offload/ram_expansion/nyx_4gb.bin");
df("sd:/switch/.packages/.offload/ram_expansion/nyx_8gb.bin");
df("sd:/switch/.packages/boot_package.ini");
df("sd:/switch/.packages/package.ini");
df("sd:/switch/.packages/reboot.ini");
df("sd:/switch/.DS_Store");
df("sd:/switch/AmiiboGenerator.nro");
df("sd:/switch/Benchmark-Toolbox.nro");
df("sd:/switch/daybreak.nro");
df("sd:/switch/DBI/translation.bin");
df("sd:/switch/haze.nro");
df("sd:/switch/hbmenu.nro");
df("sd:/switch/reboot_to_payload.nro");
df("sd:/switch/sphaira.nro");
df("sd:/switch/sys-clk-manager.nro");
#df("sd:/switch/tinfoil/loacations.conf");

# Mariko cache
df("sd:/warmboot_mariko/wb_0c.bin");
df("sd:/warmboot_mariko/wb_0d.bin");
df("sd:/warmboot_mariko/wb_0e.bin");
df("sd:/warmboot_mariko/wb_0f.bin");
df("sd:/warmboot_mariko/wb_10.bin");
df("sd:/warmboot_mariko/wb_11.bin");
df("sd:/warmboot_mariko/wb_12.bin");
df("sd:/warmboot_mariko/wb_13.bin");
df("sd:/warmboot_mariko/wb_14.bin");
df("sd:/warmboot_mariko/wb_15.bin");
#df("sd:/warmboot_mariko/wb_16.bin");
#df("sd:/warmboot_mariko/wb_17.bin");

# root directory
dd("sd:/Firmware");
dd("sd:/firmware");
dd("sd:/games");
dd("sd:/scripts");
dd("sd:/tegraexplorer");
dd("sd:/themes");
dd("sd:/.DS_Store");

df("sd:/.DS_Store");
df("sd:/emuiibo/overlay/lang/de.json");
df("sd:/emuiibo/overlay/lang/es.json");
df("sd:/emuiibo/overlay/lang/fr.json");
df("sd:/emuiibo/overlay/lang/it.json");
df("sd:/emuiibo/overlay/lang/pt-BR.json");
df("sd:/emuiibo/overlay/lang/ru.json");
df("sd:/emuiibo/overlay/lang/zh-Hans.json");
df("sd:/emuiibo/overlay/lang/zh-Hant.json");
df("sd:/BCPKG2-1-Normal-Main");
df("sd:/BCPKG2-1-Normal-Main.bin");
df("sd:/BCPKG2-2-Normal-Sub");
df("sd:/BCPKG2-2-Normal-Sub.bin");
df("sd:/BCPKG2-3-SafeMode-Main");
df("sd:/BCPKG2-3-SafeMode-Main.bin");
df("sd:/BCPKG2-4-SafeMode-Sub");
df("sd:/BCPKG2-4-SafeMode-Sub.bin");
df("sd:/BCPKG2-5-Repair-Main");
df("sd:/BCPKG2-5-Repair-Main.bin");
df("sd:/BCPKG2-6-Repair-Sub");
df("sd:/BCPKG2-6-Repair-Sub.bin");
df("sd:/boot.bis");
df("sd:/BOOT0.bin");
df("sd:/BOOT1.bin");
df("sd:/.dropbox.device");
df("sd:/exosphere.bin");
df("sd:/exosphere.ini");
df("sd:/HATS_VERSION.txt");
df("sd:/hbmenu.nro");
df("sd:/install.bat");
df("sd:/manifest.json");
df("sd:/payload.bin");
df("sd:/Read me.txt");
df("sd:/sphaira.nro");
df("sd:/tinfoil.install.log");
df("sd:/update.bin");
df("sd:/.Trash-1000");

# if update ASAP
# make directories
md("sd:/atmosphere/flags");
md("sd:/atmosphere/kips");

# restore
cd("sd:/backup/configs/controllers", "sd:/config/MissionControl/");

cf("sd:/switch/ASAP-Updater/ASAP-Updater_.nro", "sd:/switch/ASAP-Updater/ASAP-Updater.nro");
cf("sd:/bootloader/payloads/fusee.bin", "sd:/atmosphere/reboot_payload.bin");
cf("sd:/backup/configs/bluetooth_devices.bak", "sd:/atmosphere/bluetooth_devices.db");
cf("sd:/backup/configs/loader.kip", "sd:/atmosphere/kips/loader.kip");
cf("sd:/backup/configs/nyx.bak", "sd:/bootloader/nyx.ini");
cf("sd:/config/ftpsrv/config_.ini", "sd:/config/ftpsrv/config.ini");
cf("sd:/backup/configs/ftpsrv.bak", "sd:/config/ftpsrv/config.ini");
cf("sd:/config/MissionControl/missioncontrol_.ini", "sd:/config/MissionControl/missioncontrol.ini");
cf("sd:/backup/configs/missioncontrol.bak", "sd:/config/MissionControl/missioncontrol.ini");
cf("sd:/config/sphaira/config_.ini", "sd:/config/sphaira/config.ini");
#cf("sd:/backup/configs/sphaira.bak", "sd:/config/sphaira/config.ini");
cf("sd:/config/sys-clk/config_.ini", "sd:/config/sys-clk/config.ini");
cf("sd:/backup/configs/hoc-clk.bak", "sd:/config/sys-clk/config.ini");
cf("sd:/backup/configs/sys-clk.bak", "sd:/config/sys-clk/config.ini");
cf("sd:/config/sys-con/config_.ini", "sd:/config/sys-con/config.ini");
cf("sd:/backup/configs/sys-con.bak", "sd:/config/sys-con/config.ini");
cf("sd:/backup/configs/sc_dualshock3.bak", "sd:/config/sys-con/config_dualshock3.ini");
cf("sd:/backup/configs/sc_dualshock4.bak", "sd:/config/sys-con/config_dualshock4.ini");
cf("sd:/backup/configs/sc_global.bak", "sd:/config/sys-con/config_global.ini");
cf("sd:/backup/configs/sc_xbox360.bak", "sd:/config/sys-con/config_xbox360.ini");
cf("sd:/backup/configs/sc_xboxone.bak", "sd:/config/sys-con/config_xboxone.ini");
cf("sd:/backup/configs/sc_xboxorig.bak", "sd:/config/sys-con/config_xboxorig.ini");
cf("sd:/backup/configs/dbi.bak", "sd:/switch/DBI/dbi.config");
#cf("sd:/backup/configs/tf_locations.conf.bak", "sd:/switch/tinfoil/locations.conf");
#cf("sd:/backup/configs/tf_gdrive.token.bak", "sd:/switch/tinfoil/gdrive.token");
#cf("sd:/backup/configs/tf_options.json.bak", "sd:/switch/tinfoil/options.json");
cf("sd:/bootloader/update.bin", "sd:/switch/.packages/.offload/ram_expansion/hekate_4gb.bin");
cf("sd:/bootloader/update.bin", "sd:/payload.bin");

df("sd:/backup/configs/nyx.bak");
df("sd:/config/ftpsrv/config_.ini");
df("sd:/config/MissionControl/missioncontrol_.ini");
df("sd:/config/sphaira/config_.ini");
df("sd:/config/sys-clk/config_.ini");
df("sd:/config/sys-con/config_.ini");
df("sd:/switch/ASAP-Updater/ASAP-Updater_.nro");

pp(01,30)co(SILVER)pt("                                   -")co(GREEN)pt(" Done ")co(SILVER)pl("-                                   ");
wait(tw = 1000);


# ASAP Install Supporter process: DEVICE
pp(19,26)co(WHITE)pt("   [")co(ORANGE)pt(" STEP.2 ")co(WHITE)pt("]")co(MAGENTA)pl(" Select your device type   ");
pp(27,30)opDV=["* Erista [Old/Patched]", "* Mariko [IBL/Lite/OLED]"];
resDV=menu(opDV, 1);
co(BACK)

if (resDV == 0){
	dd("sd:/warmboot_mariko");
	df("sd:/backup/scripts/update.te");
}

if (resDV == 1){
	dd("sd:/switch/Reboot2payload");
	df("sd:/backup/scripts/update.te");
	df("sd:/boot.dat");
	df("sd:/boot.ini");
}

pp(24,30)co(SILVER)pt("-")co(GREEN)pt(" Install or Update Completed ")co(SILVER)pl("-");
pp(27,31)co(BACK)pl("                        ");
pp(22,32)co(ORANGE)pl("Auto Reboot to ASAP after 3 seconds");
wait(tw = 3000);
payload("sd:/payload.bin");